-- Practice Tests content: Versant Professional English Test, Set 1 — all
-- 58 real items across the 10 real task sections, newly authored.

-- Part A: Sentence Completion (10, 7-28 words, workplace register)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('sentence_completion', '{"sentence": "The quarterly report, which took several weeks to prepare, was finally submitted to the board ___ review.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["for"]}'::jsonb, 0.45, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000011', 1),
('sentence_completion', '{"sentence": "She has been leading the international expansion project ___ the beginning of the fiscal year.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["since"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000011', 2),
('sentence_completion', '{"sentence": "Although the budget was tight, the team managed to complete the project ___ schedule.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["ahead of", "on"]}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000011', 3),
('sentence_completion', '{"sentence": "The new regulations require that all employee records ___ updated annually.", "hint_word": "update"}'::jsonb, '{"acceptable_answers": ["be updated"]}'::jsonb, 0.55, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000011', 4),
('sentence_completion', '{"sentence": "He apologized to the entire department ___ the miscommunication that delayed the launch.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["for"]}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000011', 5),
('sentence_completion', '{"sentence": "The committee is reviewing several proposals, but only one ___ be selected for funding.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["will"]}'::jsonb, 0.58, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000011', 6),
('sentence_completion', '{"sentence": "Despite the challenges, the merger was completed successfully ___ the end of the quarter.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["by"]}'::jsonb, 0.60, 'C1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000011', 7),
('sentence_completion', '{"sentence": "The consultant recommended restructuring the department ___ improving overall efficiency.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["to"]}'::jsonb, 0.62, 'C1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000011', 8),
('sentence_completion', '{"sentence": "If the client approves the revised contract, the project ___ begin immediately.", "hint_word": "begin"}'::jsonb, '{"acceptable_answers": ["will begin"]}'::jsonb, 0.65, 'C1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000011', 9),
('sentence_completion', '{"sentence": "The CEO announced that the company ___ expanding into three new markets next year.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["will be", "is"]}'::jsonb, 0.68, 'C1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000011', 10);

-- Part B: Passage Reconstruction (3, 30-87 words, 2 narrative + 1 email)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('passage_reconstruction', '{"passage": "Elena had been leading a struggling sales team for six months. Instead of assigning blame, she organized weekly coaching sessions focused on practical skills. Slowly, team performance began to improve. By the end of the quarter, the team had exceeded its sales target for the first time in over a year."}'::jsonb, '{"key_points": ["Elena led a struggling sales team", "she organized weekly coaching sessions", "performance slowly improved", "the team exceeded its target by quarter end"]}'::jsonb, 52, 0.55, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000012', 1),
('passage_reconstruction', '{"passage": "A manufacturing plant experienced a sudden equipment failure during peak production. The maintenance team worked through the night to diagnose the problem. They discovered a worn component that had gone unnoticed during routine inspections. After replacing the part, production resumed the next morning with only minor delays."}'::jsonb, '{"key_points": ["a plant had a sudden equipment failure", "the maintenance team worked through the night", "they found a worn, unnoticed component", "production resumed the next morning"]}'::jsonb, 48, 0.58, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000012', 2),
('passage_reconstruction', '{"passage": "Thank you for your patience during the recent system migration. We understand that the temporary downtime affected your team''s workflow, and we sincerely apologize for any disruption caused. All services have now been fully restored, and we have implemented additional safeguards to prevent similar issues going forward."}'::jsonb, '{"key_points": ["thanks for patience during the migration", "apologizes for the downtime and disruption", "services are fully restored", "additional safeguards have been implemented"]}'::jsonb, 48, 0.56, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000012', 3);

-- Part C: Reading Comprehension (6 = 3 passages x 2 questions each, MC)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('reading_comprehension', '{"passage": "Quarterly Sales Summary: Region North sold 1,200 units, up 15% from last quarter. Region South sold 950 units, down 5%. Region East sold 1,500 units, up 20%, the highest growth of any region this quarter.", "question": "Which region had the highest growth?", "options": ["Region North", "Region South", "Region East", "None of them"]}'::jsonb, '{"correctIndex": 2}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000013', 1),
('reading_comprehension', '{"passage": "Quarterly Sales Summary: Region North sold 1,200 units, up 15% from last quarter. Region South sold 950 units, down 5%. Region East sold 1,500 units, up 20%, the highest growth of any region this quarter.", "question": "Which region''s sales declined?", "options": ["Region North", "Region South", "Region East", "All regions"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.48, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000013', 2),
('reading_comprehension', '{"passage": "Employee Handbook Excerpt: All full-time employees are entitled to 15 days of paid vacation per year, accrued monthly. Vacation requests must be submitted at least two weeks in advance and approved by a direct supervisor.", "question": "How many vacation days do full-time employees receive per year?", "options": ["10", "15", "20", "25"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.42, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000013', 3),
('reading_comprehension', '{"passage": "Employee Handbook Excerpt: All full-time employees are entitled to 15 days of paid vacation per year, accrued monthly. Vacation requests must be submitted at least two weeks in advance and approved by a direct supervisor.", "question": "How far in advance must vacation requests be submitted?", "options": ["One week", "Two weeks", "One month", "No advance notice needed"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.44, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000013', 4),
('reading_comprehension', '{"passage": "Meeting Minutes Excerpt: The marketing team proposed increasing the social media budget by 10% to support the new product launch. The finance team agreed to review the proposal and respond within one week.", "question": "What did the marketing team propose?", "options": ["Decreasing the budget", "Increasing the social media budget", "Cancelling the launch", "Hiring new staff"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000013', 5),
('reading_comprehension', '{"passage": "Meeting Minutes Excerpt: The marketing team proposed increasing the social media budget by 10% to support the new product launch. The finance team agreed to review the proposal and respond within one week.", "question": "When will finance respond to the proposal?", "options": ["Immediately", "Within one week", "Next month", "They declined to respond"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000013', 6);

-- Part D: Email Writing (2)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('email_writing', '{"prompt": "Your company recently opened a new regional office. Your manager, Ms. Okafor, has asked for your ideas about how to help new hires there feel welcome. Write an email to her suggesting three ways to improve the new office''s onboarding experience. Your suggestions must come from the following three themes: welcome packages, buddy system, local team introductions. You should include all three themes and provide supporting ideas for each of your suggestions."}'::jsonb, null, 0.58, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000014', 1),
('email_writing', '{"prompt": "Your department is launching a new internal newsletter. Your manager, Mr. Boyd, wants ideas for what content to include. Write an email to him suggesting three types of content for the newsletter. Your suggestions must come from the following three themes: employee spotlights, project updates, company announcements. You should include all three themes and provide supporting ideas for each of your suggestions."}'::jsonb, null, 0.58, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000014', 2);

-- Part E: Dictation (8, 4-14 words)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('dictation', '{"text": "The deal fell through."}'::jsonb, '{"exact": "The deal fell through."}'::jsonb, 4, 0.30, 'A2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000015', 1),
('dictation', '{"text": "She led the entire project."}'::jsonb, '{"exact": "She led the entire project."}'::jsonb, 5, 0.34, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000015', 2),
('dictation', '{"text": "They finalized the contract yesterday afternoon."}'::jsonb, '{"exact": "They finalized the contract yesterday afternoon."}'::jsonb, 6, 0.40, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000015', 3),
('dictation', '{"text": "He presented the proposal to the board."}'::jsonb, '{"exact": "He presented the proposal to the board."}'::jsonb, 7, 0.45, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000015', 4),
('dictation', '{"text": "The committee approved the revised budget this morning."}'::jsonb, '{"exact": "The committee approved the revised budget this morning."}'::jsonb, 8, 0.50, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000015', 5),
('dictation', '{"text": "She''s been overseeing international operations for three years."}'::jsonb, '{"exact": "She''s been overseeing international operations for three years."}'::jsonb, 9, 0.55, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000015', 6),
('dictation', '{"text": "The merger was completed despite significant resistance from several shareholders."}'::jsonb, '{"exact": "The merger was completed despite significant resistance from several shareholders."}'::jsonb, 11, 0.62, 'C1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000015', 7),
('dictation', '{"text": "He explained that the restructuring plan would be implemented gradually over several months."}'::jsonb, '{"exact": "He explained that the restructuring plan would be implemented gradually over several months."}'::jsonb, 13, 0.68, 'C1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000015', 8);

-- Part F: Response Selection (8, sentence + 3 options, pick most appropriate)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('response_selection', '{"text": "The client wants to reschedule the meeting.", "options": ["Sure, what time works for you?", "I enjoy meetings.", "The printer needs toner."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.35, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000016', 1),
('response_selection', '{"text": "We''re over budget this quarter.", "options": ["By how much?", "That''s a nice color.", "The meeting starts at noon."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.38, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000016', 2),
('response_selection', '{"text": "Can you send me the report by Friday?", "options": ["Yes, I''ll have it ready.", "I don''t like reports.", "The office is on the third floor."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.42, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000016', 3),
('response_selection', '{"text": "I think we should hire another developer.", "options": ["Let''s discuss the budget for that.", "The coffee machine is broken.", "He left early today."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.48, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000016', 4),
('response_selection', '{"text": "The server crashed again last night.", "options": ["Did IT fix it?", "The weather is nice today.", "She''s on vacation next week."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'technology', 'd1000000-0000-4000-8000-000000000016', 5),
('response_selection', '{"text": "Our main competitor just launched a similar product.", "options": ["We should review our strategy.", "I prefer tea over coffee.", "The parking lot is full."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.55, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000016', 6),
('response_selection', '{"text": "Would you like to lead the new initiative?", "options": ["I''d be happy to.", "The copier is out of paper.", "It rained yesterday."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000016', 7),
('response_selection', '{"text": "The shipment was delayed by customs.", "options": ["How long will it take now?", "I enjoy long walks.", "The building has five floors."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.58, 'C1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000016', 8);

-- Part G: Passage Comprehension (6 = 2 passages x 3 questions each, spoken story)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('passage_comprehension', '{"story": "The sales team missed its target for the second month in a row. The manager called a meeting to discuss what was going wrong. After listening to the team''s concerns, she realized the leads they received were outdated. She arranged for a new system to deliver fresher leads each week.", "question": "Why did the manager call a meeting?"}'::jsonb, '{"acceptable_answers": ["the team missed its target", "missed the sales target"]}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000017', 1),
('passage_comprehension', '{"story": "The sales team missed its target for the second month in a row. The manager called a meeting to discuss what was going wrong. After listening to the team''s concerns, she realized the leads they received were outdated. She arranged for a new system to deliver fresher leads each week.", "question": "What did the manager discover?"}'::jsonb, '{"acceptable_answers": ["the leads were outdated", "outdated leads"]}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000017', 2),
('passage_comprehension', '{"story": "The sales team missed its target for the second month in a row. The manager called a meeting to discuss what was going wrong. After listening to the team''s concerns, she realized the leads they received were outdated. She arranged for a new system to deliver fresher leads each week.", "question": "What did she arrange?"}'::jsonb, '{"acceptable_answers": ["a new system for fresher leads", "fresher leads each week"]}'::jsonb, 0.54, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000017', 3),
('passage_comprehension', '{"story": "A small bakery started receiving large catering orders for corporate events. At first, the owner struggled to keep up with demand using the original kitchen. She decided to rent additional kitchen space nearby. Within months, the bakery was handling twice as many orders as before.", "question": "What kind of orders did the bakery start receiving?"}'::jsonb, '{"acceptable_answers": ["large catering orders", "corporate catering orders"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000017', 4),
('passage_comprehension', '{"story": "A small bakery started receiving large catering orders for corporate events. At first, the owner struggled to keep up with demand using the original kitchen. She decided to rent additional kitchen space nearby. Within months, the bakery was handling twice as many orders as before.", "question": "What did the owner struggle with initially?"}'::jsonb, '{"acceptable_answers": ["keeping up with demand", "meeting the demand"]}'::jsonb, 0.50, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000017', 5),
('passage_comprehension', '{"story": "A small bakery started receiving large catering orders for corporate events. At first, the owner struggled to keep up with demand using the original kitchen. She decided to rent additional kitchen space nearby. Within months, the bakery was handling twice as many orders as before.", "question": "What did she decide to do?"}'::jsonb, '{"acceptable_answers": ["rent additional kitchen space", "rent more kitchen space"]}'::jsonb, 0.52, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000017', 6);

-- Part H: Repeat (10, 4-17 words)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('repeats', '{"text": "The deal closed today."}'::jsonb, '{"exact": "The deal closed today."}'::jsonb, 4, 0.28, 'A2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000018', 1),
('repeats', '{"text": "She manages the entire region."}'::jsonb, '{"exact": "She manages the entire region."}'::jsonb, 5, 0.32, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000018', 2),
('repeats', '{"text": "He proposed a new strategy yesterday."}'::jsonb, '{"exact": "He proposed a new strategy yesterday."}'::jsonb, 6, 0.36, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000018', 3),
('repeats', '{"text": "The board approved the budget unanimously."}'::jsonb, '{"exact": "The board approved the budget unanimously."}'::jsonb, 6, 0.40, 'B1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000018', 4),
('repeats', '{"text": "She''s been negotiating this contract for weeks."}'::jsonb, '{"exact": "She''s been negotiating this contract for weeks."}'::jsonb, 7, 0.46, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000018', 5),
('repeats', '{"text": "They decided to delay the launch until spring."}'::jsonb, '{"exact": "They decided to delay the launch until spring."}'::jsonb, 8, 0.50, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000018', 6),
('repeats', '{"text": "He explained that the merger would take several months."}'::jsonb, '{"exact": "He explained that the merger would take several months."}'::jsonb, 9, 0.55, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000018', 7),
('repeats', '{"text": "The team worked overtime to meet the client''s unexpected deadline."}'::jsonb, '{"exact": "The team worked overtime to meet the client''s unexpected deadline."}'::jsonb, 10, 0.60, 'C1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000018', 8),
('repeats', '{"text": "She mentioned that the restructuring had affected nearly every department in the company."}'::jsonb, '{"exact": "She mentioned that the restructuring had affected nearly every department in the company."}'::jsonb, 13, 0.66, 'C1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000018', 9),
('repeats', '{"text": "He explained that the new policy would require every manager to attend additional training sessions."}'::jsonb, '{"exact": "He explained that the new policy would require every manager to attend additional training sessions."}'::jsonb, 15, 0.72, 'C1', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000018', 10);

-- Part I: Speaking Situations (2, 10s prep + 60s open response)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('speaking_situations', '{"situation": "Your team missed an important deadline because of a miscommunication. Your manager asks you to explain what happened. What would you say to her?"}'::jsonb, null, 0.55, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000019', 1),
('speaking_situations', '{"situation": "A colleague keeps interrupting you during meetings. You decide to address it privately. What would you say to him?"}'::jsonb, null, 0.52, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-000000000019', 2);

-- Part J: Story Retellings (3)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('story_retelling', '{"story": "The new intern accidentally sent a confidential file to the wrong client. She immediately told her supervisor instead of hiding the mistake. Her supervisor appreciated her honesty and helped resolve the issue quickly. The client was understanding once they learned how transparently it had been handled."}'::jsonb, null, 47, 0.52, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-00000000001a', 1),
('story_retelling', '{"story": "A small startup was struggling to attract investors. The founder revised the pitch to focus on real customer testimonials instead of only financial projections. The new approach resonated much more with potential investors. Within a month, the startup secured its first major round of funding."}'::jsonb, null, 46, 0.55, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-00000000001a', 2),
('story_retelling', '{"story": "An employee noticed that a long-standing process was wasting significant time every week. Instead of simply complaining, she proposed a simpler alternative to her manager. The manager tested the new process for a month. It saved the team several hours a week, and it was adopted company-wide."}'::jsonb, null, 48, 0.54, 'B2', 'approved', 'exam', 'business', 'd1000000-0000-4000-8000-00000000001a', 3);
