-- Practice Tests content: Versant Professional English Test, Set 2 — 58
-- freshly authored items (HR/manufacturing/logistics topics, distinct
-- from Set 1).

-- Part A: Sentence Completion (10)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('sentence_completion', '{"sentence": "The recruitment drive, which lasted nearly two months, finally resulted in ten new hires ___ the engineering team.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["for"]}'::jsonb, 0.45, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000011', 1),
('sentence_completion', '{"sentence": "He has been supervising the warehouse operations ___ the company relocated last spring.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["since"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000011', 2),
('sentence_completion', '{"sentence": "Even though the factory faced staffing shortages, production stayed ___ schedule.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["on", "ahead of"]}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000011', 3),
('sentence_completion', '{"sentence": "Company policy requires that all safety inspections ___ documented in detail.", "hint_word": "document"}'::jsonb, '{"acceptable_answers": ["be documented"]}'::jsonb, 0.55, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000011', 4),
('sentence_completion', '{"sentence": "She apologized to the logistics team ___ the confusion over the delivery schedule.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["for"]}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000011', 5),
('sentence_completion', '{"sentence": "Several candidates applied for the role, but only one ___ be offered the position.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["will"]}'::jsonb, 0.58, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000011', 6),
('sentence_completion', '{"sentence": "Despite a shortage of parts, the assembly line resumed full operation ___ the end of the week.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["by"]}'::jsonb, 0.60, 'C1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000011', 7),
('sentence_completion', '{"sentence": "The consultant suggested reorganizing the shipping schedule ___ reducing delivery delays.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["to"]}'::jsonb, 0.62, 'C1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000011', 8),
('sentence_completion', '{"sentence": "If the supplier confirms the order today, the shipment ___ depart tomorrow morning.", "hint_word": "depart"}'::jsonb, '{"acceptable_answers": ["will depart"]}'::jsonb, 0.65, 'C1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000011', 9),
('sentence_completion', '{"sentence": "The director confirmed that the factory ___ adding a second production shift next month.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["will be", "is"]}'::jsonb, 0.68, 'C1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000011', 10);

-- Part B: Passage Reconstruction (3, 2 narrative + 1 email)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('passage_reconstruction', '{"passage": "A new HR manager inherited a team with low morale and high turnover. Rather than making immediate changes, she spent her first month listening to employees individually. Based on their feedback, she introduced flexible scheduling and recognition awards. Within six months, turnover had dropped noticeably."}'::jsonb, '{"key_points": ["a new HR manager inherited a team with low morale", "she spent a month listening to employees", "she introduced flexible scheduling and awards", "turnover dropped within six months"]}'::jsonb, 46, 0.55, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000012', 1),
('passage_reconstruction', '{"passage": "A logistics company noticed repeated delays at one of its regional hubs. After investigating, managers discovered an outdated routing system was the main cause. They installed updated software and retrained the dispatch team. Delivery times at that hub improved significantly within weeks."}'::jsonb, '{"key_points": ["a company noticed delays at a regional hub", "an outdated routing system was the cause", "they installed new software and retrained staff", "delivery times improved within weeks"]}'::jsonb, 42, 0.56, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000012', 2),
('passage_reconstruction', '{"passage": "Thank you for raising your concerns about the recent shift changes. We understand this has affected several employees'' schedules, and we apologize for the short notice given. We are reviewing the policy and will share an updated schedule by the end of this week."}'::jsonb, '{"key_points": ["thanks for raising concerns about shift changes", "apologizes for the short notice", "the policy is being reviewed", "an updated schedule will be shared by week''s end"]}'::jsonb, 44, 0.56, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000012', 3);

-- Part C: Reading Comprehension (6 = 3 passages x 2 questions each)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('reading_comprehension', '{"passage": "Shift Schedule Notice: Shift A runs 6am-2pm with 12 workers. Shift B runs 2pm-10pm with 15 workers, the largest shift. Shift C runs 10pm-6am with 8 workers, the smallest shift.", "question": "Which shift has the most workers?", "options": ["Shift A", "Shift B", "Shift C", "All equal"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000013', 1),
('reading_comprehension', '{"passage": "Shift Schedule Notice: Shift A runs 6am-2pm with 12 workers. Shift B runs 2pm-10pm with 15 workers, the largest shift. Shift C runs 10pm-6am with 8 workers, the smallest shift.", "question": "Which shift has the fewest workers?", "options": ["Shift A", "Shift B", "Shift C", "All equal"]}'::jsonb, '{"correctIndex": 2}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000013', 2),
('reading_comprehension', '{"passage": "HR Policy Excerpt: New employees complete a 90-day probationary period before becoming eligible for full benefits. Performance reviews are conducted at the 30-day and 90-day marks.", "question": "How long is the probationary period?", "options": ["30 days", "60 days", "90 days", "120 days"]}'::jsonb, '{"correctIndex": 2}'::jsonb, 0.42, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000013', 3),
('reading_comprehension', '{"passage": "HR Policy Excerpt: New employees complete a 90-day probationary period before becoming eligible for full benefits. Performance reviews are conducted at the 30-day and 90-day marks.", "question": "When are performance reviews conducted?", "options": ["Only at 90 days", "At 30 and 90 days", "Every month", "Only at hiring"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.44, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000013', 4),
('reading_comprehension', '{"passage": "Warehouse Memo: The new inventory system will go live next Monday. All staff must complete the online training module before then. Supervisors will verify completion by Friday.", "question": "When does the new system go live?", "options": ["This Friday", "Next Monday", "Next Friday", "Immediately"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.45, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000013', 5),
('reading_comprehension', '{"passage": "Warehouse Memo: The new inventory system will go live next Monday. All staff must complete the online training module before then. Supervisors will verify completion by Friday.", "question": "Who verifies that training is completed?", "options": ["HR", "Supervisors", "IT", "No one"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000013', 6);

-- Part D: Email Writing (2)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('email_writing', '{"prompt": "Your warehouse has had an increase in minor safety incidents recently. Your manager, Mr. Alves, wants ideas for improving safety without large new investments. Write an email to him suggesting three ways to improve safety. Your suggestions must come from the following three themes: refresher training, clearer signage, regular equipment checks. You should include all three themes and provide supporting ideas for each of your suggestions."}'::jsonb, null, 0.58, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000014', 1),
('email_writing', '{"prompt": "Your team is planning its annual recruitment drive. Your manager, Ms. Lindqvist, wants ideas for attracting more qualified applicants. Write an email to her suggesting three ways to improve the recruitment process. Your suggestions must come from the following three themes: referral bonuses, university partnerships, improved job postings. You should include all three themes and provide supporting ideas for each of your suggestions."}'::jsonb, null, 0.58, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000014', 2);

-- Part E: Dictation (8)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('dictation', '{"text": "The shift just ended."}'::jsonb, '{"exact": "The shift just ended."}'::jsonb, 4, 0.30, 'A2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000015', 1),
('dictation', '{"text": "She supervises the entire warehouse."}'::jsonb, '{"exact": "She supervises the entire warehouse."}'::jsonb, 5, 0.34, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000015', 2),
('dictation', '{"text": "They finalized the hiring decisions yesterday."}'::jsonb, '{"exact": "They finalized the hiring decisions yesterday."}'::jsonb, 6, 0.40, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000015', 3),
('dictation', '{"text": "He presented the safety report to management."}'::jsonb, '{"exact": "He presented the safety report to management."}'::jsonb, 7, 0.45, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000015', 4),
('dictation', '{"text": "The committee approved the revised shift schedule today."}'::jsonb, '{"exact": "The committee approved the revised shift schedule today."}'::jsonb, 8, 0.50, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000015', 5),
('dictation', '{"text": "She''s been overseeing warehouse logistics for three years."}'::jsonb, '{"exact": "She''s been overseeing warehouse logistics for three years."}'::jsonb, 8, 0.55, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000015', 6),
('dictation', '{"text": "The hiring process was delayed despite strong interest from applicants."}'::jsonb, '{"exact": "The hiring process was delayed despite strong interest from applicants."}'::jsonb, 10, 0.62, 'C1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000015', 7),
('dictation', '{"text": "He explained that the new routing system would be implemented gradually across all hubs."}'::jsonb, '{"exact": "He explained that the new routing system would be implemented gradually across all hubs."}'::jsonb, 14, 0.68, 'C1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000015', 8);

-- Part F: Response Selection (8)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('response_selection', '{"text": "The candidate wants to reschedule the interview.", "options": ["Sure, what day works for you?", "I enjoy interviews.", "The printer needs toner."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.35, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000016', 1),
('response_selection', '{"text": "We''re short-staffed on the night shift.", "options": ["How many people do we need?", "That''s a nice color.", "The meeting starts at noon."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.38, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000016', 2),
('response_selection', '{"text": "Can you send me the inventory count by Friday?", "options": ["Yes, I''ll have it ready.", "I don''t like counting.", "The office is on the third floor."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.42, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000016', 3),
('response_selection', '{"text": "I think we should hire another forklift operator.", "options": ["Let''s discuss the budget for that.", "The coffee machine is broken.", "He left early today."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.48, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000016', 4),
('response_selection', '{"text": "The conveyor belt stopped working again.", "options": ["Did maintenance check it?", "The weather is nice today.", "She''s on vacation next week."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000016', 5),
('response_selection', '{"text": "Our competitor is offering faster shipping times.", "options": ["We should review our logistics process.", "I prefer tea over coffee.", "The parking lot is full."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.55, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000016', 6),
('response_selection', '{"text": "Would you like to lead the safety committee?", "options": ["I''d be happy to.", "The copier is out of paper.", "It rained yesterday."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000016', 7),
('response_selection', '{"text": "The shipment was held up at the border.", "options": ["How long will it take now?", "I enjoy long walks.", "The building has five floors."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.58, 'C1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000016', 8);

-- Part G: Passage Comprehension (6 = 2 passages x 3 questions)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('passage_comprehension', '{"story": "A factory noticed a rise in minor injuries over several months. Supervisors reviewed incident reports and found most injuries happened near the loading dock. They installed better lighting and added non-slip flooring. Injury reports dropped significantly the following quarter.", "question": "What did supervisors notice?"}'::jsonb, '{"acceptable_answers": ["a rise in minor injuries", "more minor injuries"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000017', 1),
('passage_comprehension', '{"story": "A factory noticed a rise in minor injuries over several months. Supervisors reviewed incident reports and found most injuries happened near the loading dock. They installed better lighting and added non-slip flooring. Injury reports dropped significantly the following quarter.", "question": "Where did most injuries happen?"}'::jsonb, '{"acceptable_answers": ["near the loading dock", "the loading dock"]}'::jsonb, 0.50, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000017', 2),
('passage_comprehension', '{"story": "A factory noticed a rise in minor injuries over several months. Supervisors reviewed incident reports and found most injuries happened near the loading dock. They installed better lighting and added non-slip flooring. Injury reports dropped significantly the following quarter.", "question": "What did they install?"}'::jsonb, '{"acceptable_answers": ["better lighting and non-slip flooring", "lighting and non-slip flooring"]}'::jsonb, 0.52, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000017', 3),
('passage_comprehension', '{"story": "A distribution company kept losing packages during transit. Managers traced the problem to a single unreliable courier partner. They switched to a more reputable courier for high-value shipments. Customer complaints about lost packages nearly disappeared.", "question": "What problem did the company have?"}'::jsonb, '{"acceptable_answers": ["losing packages during transit", "lost packages"]}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000017', 4),
('passage_comprehension', '{"story": "A distribution company kept losing packages during transit. Managers traced the problem to a single unreliable courier partner. They switched to a more reputable courier for high-value shipments. Customer complaints about lost packages nearly disappeared.", "question": "What did managers trace the problem to?"}'::jsonb, '{"acceptable_answers": ["an unreliable courier partner", "the courier partner"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000017', 5),
('passage_comprehension', '{"story": "A distribution company kept losing packages during transit. Managers traced the problem to a single unreliable courier partner. They switched to a more reputable courier for high-value shipments. Customer complaints about lost packages nearly disappeared.", "question": "What did they do about it?"}'::jsonb, '{"acceptable_answers": ["switched to a more reputable courier", "changed couriers"]}'::jsonb, 0.50, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000017', 6);

-- Part H: Repeat (10)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('repeats', '{"text": "The shift just started."}'::jsonb, '{"exact": "The shift just started."}'::jsonb, 4, 0.28, 'A2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000018', 1),
('repeats', '{"text": "She oversees the whole warehouse."}'::jsonb, '{"exact": "She oversees the whole warehouse."}'::jsonb, 5, 0.32, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000018', 2),
('repeats', '{"text": "He proposed a new safety policy yesterday."}'::jsonb, '{"exact": "He proposed a new safety policy yesterday."}'::jsonb, 7, 0.36, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000018', 3),
('repeats', '{"text": "The board approved the hiring plan unanimously."}'::jsonb, '{"exact": "The board approved the hiring plan unanimously."}'::jsonb, 7, 0.40, 'B1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000018', 4),
('repeats', '{"text": "She''s been negotiating this contract for weeks."}'::jsonb, '{"exact": "She''s been negotiating this contract for weeks."}'::jsonb, 7, 0.46, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000018', 5),
('repeats', '{"text": "They decided to delay the rollout until spring."}'::jsonb, '{"exact": "They decided to delay the rollout until spring."}'::jsonb, 8, 0.50, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000018', 6),
('repeats', '{"text": "He explained that the relocation would take several months."}'::jsonb, '{"exact": "He explained that the relocation would take several months."}'::jsonb, 9, 0.55, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000018', 7),
('repeats', '{"text": "The team worked overtime to meet the supplier''s unexpected deadline."}'::jsonb, '{"exact": "The team worked overtime to meet the supplier''s unexpected deadline."}'::jsonb, 10, 0.60, 'C1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000018', 8),
('repeats', '{"text": "She mentioned that the reorganization had affected nearly every shift in the plant."}'::jsonb, '{"exact": "She mentioned that the reorganization had affected nearly every shift in the plant."}'::jsonb, 13, 0.66, 'C1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000018', 9),
('repeats', '{"text": "He explained that the new safety policy would require every supervisor to attend additional training."}'::jsonb, '{"exact": "He explained that the new safety policy would require every supervisor to attend additional training."}'::jsonb, 14, 0.72, 'C1', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000018', 10);

-- Part I: Speaking Situations (2)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('speaking_situations', '{"situation": "A shipment you were responsible for arrived at the wrong warehouse. Your supervisor asks you to explain what happened. What would you say to her?"}'::jsonb, null, 0.55, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000019', 1),
('speaking_situations', '{"situation": "A new team member keeps missing safety procedures. You decide to address it with him directly. What would you say?"}'::jsonb, null, 0.52, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-000000000019', 2);

-- Part J: Story Retellings (3)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('story_retelling', '{"story": "A warehouse supervisor noticed one employee consistently exceeded productivity targets. Instead of simply praising her privately, he asked her to share her methods with the team. Several coworkers adopted her approach. Overall warehouse productivity rose noticeably within a month."}'::jsonb, null, 42, 0.52, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-00000000001a', 1),
('story_retelling', '{"story": "A manufacturing company struggled with a high rate of equipment breakdowns. An engineer suggested switching to a preventive maintenance schedule instead of fixing issues as they arose. Management approved a trial period. Breakdowns dropped sharply, saving the company significant repair costs."}'::jsonb, null, 45, 0.55, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-00000000001a', 2),
('story_retelling', '{"story": "A recruiter noticed that strong candidates often dropped out during a lengthy interview process. She proposed condensing it from five stages to three. Hiring managers were initially hesitant to change the process. After a trial run, both candidate satisfaction and hiring speed improved significantly."}'::jsonb, null, 47, 0.56, 'B2', 'approved', 'exam', 'business', 'd2000000-0000-4000-8000-00000000001a', 3);
