-- Practice Tests content: Versant Professional English Test, Set 3 — 58
-- freshly authored items (healthcare/retail topics, distinct from Sets 1-2).

-- Part A: Sentence Completion (10)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('sentence_completion', '{"sentence": "The clinic''s new scheduling software, which took months to implement, finally went live ___ all departments.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["across", "for"]}'::jsonb, 0.45, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000011', 1),
('sentence_completion', '{"sentence": "She has been managing the pharmacy ___ the previous manager retired last year.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["since"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000011', 2),
('sentence_completion', '{"sentence": "Even with limited staff, the store kept its inventory updates ___ schedule.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["on", "ahead of"]}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000011', 3),
('sentence_completion', '{"sentence": "Hospital policy requires that all patient records ___ updated within 24 hours.", "hint_word": "update"}'::jsonb, '{"acceptable_answers": ["be updated"]}'::jsonb, 0.55, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000011', 4),
('sentence_completion', '{"sentence": "He apologized to the customer ___ the long wait at checkout.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["for"]}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000011', 5),
('sentence_completion', '{"sentence": "Several suppliers submitted bids, but only one ___ be awarded the contract.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["will"]}'::jsonb, 0.58, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000011', 6),
('sentence_completion', '{"sentence": "Despite a shortage of nurses, the ward maintained adequate coverage ___ the end of the month.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["by"]}'::jsonb, 0.60, 'C1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000011', 7),
('sentence_completion', '{"sentence": "The consultant recommended reorganizing the checkout area ___ reducing customer wait times.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["to"]}'::jsonb, 0.62, 'C1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000011', 8),
('sentence_completion', '{"sentence": "If the supplier confirms availability today, the new stock ___ arrive by Thursday.", "hint_word": "arrive"}'::jsonb, '{"acceptable_answers": ["will arrive"]}'::jsonb, 0.65, 'C1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000011', 9),
('sentence_completion', '{"sentence": "The director confirmed that the clinic ___ opening a second location next year.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["will be", "is"]}'::jsonb, 0.68, 'C1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000011', 10);

-- Part B: Passage Reconstruction (3, 2 narrative + 1 email)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('passage_reconstruction', '{"passage": "A pharmacy began receiving frequent complaints about long wait times. The manager analyzed the busiest hours and realized staffing did not match demand. She adjusted the schedule to add an extra pharmacist during peak hours. Complaints about wait times dropped significantly within a month."}'::jsonb, '{"key_points": ["a pharmacy received complaints about wait times", "the manager found staffing did not match demand", "she added an extra pharmacist at peak hours", "complaints dropped within a month"]}'::jsonb, 46, 0.55, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000012', 1),
('passage_reconstruction', '{"passage": "A retail chain noticed declining sales at one of its stores. Regional managers visited the location and interviewed staff. They discovered the store layout was confusing customers. After redesigning the layout, sales at that location recovered within two months."}'::jsonb, '{"key_points": ["a retail chain noticed declining sales", "managers interviewed staff at the store", "the layout was confusing customers", "sales recovered after a redesign"]}'::jsonb, 42, 0.56, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000012', 2),
('passage_reconstruction', '{"passage": "Thank you for your feedback regarding the recent changes to our appointment system. We understand this created some confusion for patients this month, and we sincerely apologize. We have updated our instructions and added staff to assist with scheduling questions going forward."}'::jsonb, '{"key_points": ["thanks for feedback about the appointment system", "apologizes for the confusion", "instructions have been updated", "staff were added to help with scheduling"]}'::jsonb, 42, 0.56, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000012', 3);

-- Part C: Reading Comprehension (6 = 3 passages x 2 questions each)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('reading_comprehension', '{"passage": "Pharmacy Inventory Report: Aisle 1 has 300 units of pain relievers, fully stocked. Aisle 2 has 50 units of cold medicine, low stock. Aisle 3 has 180 units of vitamins, moderately stocked.", "question": "Which aisle has low stock?", "options": ["Aisle 1", "Aisle 2", "Aisle 3", "None of them"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000013', 1),
('reading_comprehension', '{"passage": "Pharmacy Inventory Report: Aisle 1 has 300 units of pain relievers, fully stocked. Aisle 2 has 50 units of cold medicine, low stock. Aisle 3 has 180 units of vitamins, moderately stocked.", "question": "Which aisle is fully stocked?", "options": ["Aisle 1", "Aisle 2", "Aisle 3", "All of them"]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000013', 2),
('reading_comprehension', '{"passage": "Clinic Policy Excerpt: Patients must arrive 15 minutes before their appointment to complete paperwork. Appointments running more than 10 minutes late may need to be rescheduled.", "question": "How early must patients arrive?", "options": ["5 minutes", "10 minutes", "15 minutes", "30 minutes"]}'::jsonb, '{"correctIndex": 2}'::jsonb, 0.42, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000013', 3),
('reading_comprehension', '{"passage": "Clinic Policy Excerpt: Patients must arrive 15 minutes before their appointment to complete paperwork. Appointments running more than 10 minutes late may need to be rescheduled.", "question": "When might an appointment be rescheduled?", "options": ["If paperwork is missing", "If the patient is over 10 minutes late", "If it is a first visit", "Never"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.44, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000013', 4),
('reading_comprehension', '{"passage": "Store Memo: The new point-of-sale system launches next Tuesday. All cashiers must complete the training video before then. Shift leads will confirm completion by Monday.", "question": "When does the new system launch?", "options": ["This Monday", "Next Tuesday", "Next Monday", "Immediately"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.45, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000013', 5),
('reading_comprehension', '{"passage": "Store Memo: The new point-of-sale system launches next Tuesday. All cashiers must complete the training video before then. Shift leads will confirm completion by Monday.", "question": "Who confirms training completion?", "options": ["HR", "Shift leads", "IT", "No one"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000013', 6);

-- Part D: Email Writing (2)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('email_writing', '{"prompt": "Your clinic has had an increase in patient wait-time complaints. Your manager, Dr. Nilsson, wants ideas for improving the patient experience without hiring more staff. Write an email to her suggesting three ways to achieve this. Your suggestions must come from the following three themes: online check-in, better appointment spacing, a waiting-room update system. You should include all three themes and provide supporting ideas for each of your suggestions."}'::jsonb, null, 0.58, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000014', 1),
('email_writing', '{"prompt": "Your store is planning to redesign its layout. Your manager, Mr. Castillo, wants ideas for the new design. Write an email to him suggesting three priorities for the redesign. Your suggestions must come from the following three themes: clearer signage, wider aisles, a more visible checkout area. You should include all three themes and provide supporting ideas for each of your suggestions."}'::jsonb, null, 0.58, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000014', 2);

-- Part E: Dictation (8)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('dictation', '{"text": "The clinic just opened."}'::jsonb, '{"exact": "The clinic just opened."}'::jsonb, 4, 0.30, 'A2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000015', 1),
('dictation', '{"text": "She manages the entire pharmacy."}'::jsonb, '{"exact": "She manages the entire pharmacy."}'::jsonb, 5, 0.34, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000015', 2),
('dictation', '{"text": "They finalized the store layout yesterday."}'::jsonb, '{"exact": "They finalized the store layout yesterday."}'::jsonb, 6, 0.40, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000015', 3),
('dictation', '{"text": "He presented the inventory report to management."}'::jsonb, '{"exact": "He presented the inventory report to management."}'::jsonb, 7, 0.45, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000015', 4),
('dictation', '{"text": "The committee approved the revised appointment system today."}'::jsonb, '{"exact": "The committee approved the revised appointment system today."}'::jsonb, 8, 0.50, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000015', 5),
('dictation', '{"text": "She''s been managing patient records for three years."}'::jsonb, '{"exact": "She''s been managing patient records for three years."}'::jsonb, 8, 0.55, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000015', 6),
('dictation', '{"text": "The renovation was delayed despite strong support from staff."}'::jsonb, '{"exact": "The renovation was delayed despite strong support from staff."}'::jsonb, 10, 0.62, 'C1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000015', 7),
('dictation', '{"text": "He explained that the new system would be rolled out gradually across all branches."}'::jsonb, '{"exact": "He explained that the new system would be rolled out gradually across all branches."}'::jsonb, 14, 0.68, 'C1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000015', 8);

-- Part F: Response Selection (8)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('response_selection', '{"text": "The patient wants to reschedule her appointment.", "options": ["Sure, what day works for you?", "I enjoy appointments.", "The printer needs toner."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.35, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000016', 1),
('response_selection', '{"text": "We''re low on stock for cold medicine.", "options": ["How much do we need to order?", "That''s a nice color.", "The meeting starts at noon."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.38, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000016', 2),
('response_selection', '{"text": "Can you send me the sales figures by Friday?", "options": ["Yes, I''ll have them ready.", "I don''t like figures.", "The office is on the third floor."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.42, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000016', 3),
('response_selection', '{"text": "I think we should hire another pharmacist.", "options": ["Let''s discuss the budget for that.", "The coffee machine is broken.", "He left early today."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.48, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000016', 4),
('response_selection', '{"text": "The checkout system crashed again.", "options": ["Did IT fix it?", "The weather is nice today.", "She''s on vacation next week."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'technology', 'd3000000-0000-4000-8000-000000000016', 5),
('response_selection', '{"text": "Our competitor opened a store nearby.", "options": ["We should review our pricing strategy.", "I prefer tea over coffee.", "The parking lot is full."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.55, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000016', 6),
('response_selection', '{"text": "Would you like to lead the new patient-care initiative?", "options": ["I''d be happy to.", "The copier is out of paper.", "It rained yesterday."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000016', 7),
('response_selection', '{"text": "The new stock was delayed by the supplier.", "options": ["How long will it take now?", "I enjoy long walks.", "The building has five floors."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.58, 'C1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000016', 8);

-- Part G: Passage Comprehension (6 = 2 passages x 3 questions)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('passage_comprehension', '{"story": "A clinic kept receiving complaints about confusing appointment reminders. The office manager reviewed the message templates and found them too technical. She rewrote them in simpler language. Patient confusion dropped sharply after the change.", "question": "What complaints was the clinic receiving?"}'::jsonb, '{"acceptable_answers": ["complaints about confusing reminders", "confusing appointment reminders"]}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000017', 1),
('passage_comprehension', '{"story": "A clinic kept receiving complaints about confusing appointment reminders. The office manager reviewed the message templates and found them too technical. She rewrote them in simpler language. Patient confusion dropped sharply after the change.", "question": "What did the manager find?"}'::jsonb, '{"acceptable_answers": ["the templates were too technical", "they were too technical"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000017', 2),
('passage_comprehension', '{"story": "A clinic kept receiving complaints about confusing appointment reminders. The office manager reviewed the message templates and found them too technical. She rewrote them in simpler language. Patient confusion dropped sharply after the change.", "question": "What did she do?"}'::jsonb, '{"acceptable_answers": ["rewrote them in simpler language", "simplified the language"]}'::jsonb, 0.50, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000017', 3),
('passage_comprehension', '{"story": "A retail store noticed many customers abandoned their carts at checkout. Staff observed that the line moved very slowly during busy hours. Management added a second register during peak times. Customer complaints about checkout nearly disappeared.", "question": "What did staff observe?"}'::jsonb, '{"acceptable_answers": ["the line moved slowly", "slow checkout lines"]}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000017', 4),
('passage_comprehension', '{"story": "A retail store noticed many customers abandoned their carts at checkout. Staff observed that the line moved very slowly during busy hours. Management added a second register during peak times. Customer complaints about checkout nearly disappeared.", "question": "What did management do?"}'::jsonb, '{"acceptable_answers": ["added a second register", "opened another register"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000017', 5),
('passage_comprehension', '{"story": "A retail store noticed many customers abandoned their carts at checkout. Staff observed that the line moved very slowly during busy hours. Management added a second register during peak times. Customer complaints about checkout nearly disappeared.", "question": "What happened to complaints afterward?"}'::jsonb, '{"acceptable_answers": ["they nearly disappeared", "they dropped a lot"]}'::jsonb, 0.50, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000017', 6);

-- Part H: Repeat (10)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('repeats', '{"text": "The clinic just closed."}'::jsonb, '{"exact": "The clinic just closed."}'::jsonb, 4, 0.28, 'A2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000018', 1),
('repeats', '{"text": "She manages the whole pharmacy."}'::jsonb, '{"exact": "She manages the whole pharmacy."}'::jsonb, 5, 0.32, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000018', 2),
('repeats', '{"text": "He proposed a new layout yesterday."}'::jsonb, '{"exact": "He proposed a new layout yesterday."}'::jsonb, 6, 0.36, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000018', 3),
('repeats', '{"text": "The board approved the renovation plan unanimously."}'::jsonb, '{"exact": "The board approved the renovation plan unanimously."}'::jsonb, 7, 0.40, 'B1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000018', 4),
('repeats', '{"text": "She''s been negotiating this supply contract for weeks."}'::jsonb, '{"exact": "She''s been negotiating this supply contract for weeks."}'::jsonb, 8, 0.46, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000018', 5),
('repeats', '{"text": "They decided to delay the opening until spring."}'::jsonb, '{"exact": "They decided to delay the opening until spring."}'::jsonb, 8, 0.50, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000018', 6),
('repeats', '{"text": "He explained that the renovation would take several months."}'::jsonb, '{"exact": "He explained that the renovation would take several months."}'::jsonb, 9, 0.55, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000018', 7),
('repeats', '{"text": "The team worked overtime to meet the supplier''s unexpected deadline."}'::jsonb, '{"exact": "The team worked overtime to meet the supplier''s unexpected deadline."}'::jsonb, 10, 0.60, 'C1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000018', 8),
('repeats', '{"text": "She mentioned that the new system had affected nearly every department in the clinic."}'::jsonb, '{"exact": "She mentioned that the new system had affected nearly every department in the clinic."}'::jsonb, 14, 0.66, 'C1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000018', 9),
('repeats', '{"text": "He explained that the new policy would require every employee to complete additional training sessions."}'::jsonb, '{"exact": "He explained that the new policy would require every employee to complete additional training sessions."}'::jsonb, 15, 0.72, 'C1', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000018', 10);

-- Part I: Speaking Situations (2)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('speaking_situations', '{"situation": "A patient complains that they waited far longer than expected for their appointment. You are the front-desk staff member who greets them. What would you say to the patient?"}'::jsonb, null, 0.55, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000019', 1),
('speaking_situations', '{"situation": "A coworker keeps leaving the stockroom disorganized despite reminders. You decide to address it with her directly. What would you say?"}'::jsonb, null, 0.52, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-000000000019', 2);

-- Part J: Story Retellings (3)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('story_retelling', '{"story": "A pharmacy technician noticed a pattern of prescription errors during busy afternoons. Instead of ignoring it, she suggested a double-check system for that time of day. Her manager approved a trial period. Prescription errors during afternoons dropped to almost zero."}'::jsonb, null, 44, 0.52, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-00000000001a', 1),
('story_retelling', '{"story": "A retail manager noticed customers often left the store without finding what they needed. She rearranged popular items closer to the entrance. She also trained staff to greet customers proactively. Within weeks, customer satisfaction scores improved noticeably."}'::jsonb, null, 42, 0.54, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-00000000001a', 2),
('story_retelling', '{"story": "A nurse noticed that new patients often seemed confused about hospital procedures. She created a simple one-page guide explaining what to expect during their visit. The guide was distributed at check-in. Patient questions at the front desk decreased significantly afterward."}'::jsonb, null, 44, 0.53, 'B2', 'approved', 'exam', 'business', 'd3000000-0000-4000-8000-00000000001a', 3);
