-- Practice Tests content: Versant Professional English Test, Set 4 — 58
-- freshly authored items (education/hospitality topics, distinct from
-- Sets 1-3).

-- Part A: Sentence Completion (10)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('sentence_completion', '{"sentence": "The university''s new enrollment system, which took a year to build, finally launched ___ all departments.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["across", "for"]}'::jsonb, 0.45, 'B1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000011', 1),
('sentence_completion', '{"sentence": "She has been managing the front desk ___ the hotel opened three years ago.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["since"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000011', 2),
('sentence_completion', '{"sentence": "Even with a full house, the hotel kept check-in times ___ schedule.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["on", "ahead of"]}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000011', 3),
('sentence_completion', '{"sentence": "University policy requires that all grade submissions ___ finalized within one week.", "hint_word": "finalize"}'::jsonb, '{"acceptable_answers": ["be finalized"]}'::jsonb, 0.55, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000011', 4),
('sentence_completion', '{"sentence": "She apologized to the guest ___ the mix-up with his room reservation.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["for"]}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000011', 5),
('sentence_completion', '{"sentence": "Several students applied for the scholarship, but only one ___ be selected.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["will"]}'::jsonb, 0.58, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000011', 6),
('sentence_completion', '{"sentence": "Despite a shortage of rooms, the hotel accommodated every guest ___ the weekend.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["by"]}'::jsonb, 0.60, 'C1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000011', 7),
('sentence_completion', '{"sentence": "The consultant recommended restructuring the curriculum ___ improving student outcomes.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["to"]}'::jsonb, 0.62, 'C1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000011', 8),
('sentence_completion', '{"sentence": "If the renovation finishes on time, the new wing ___ open by August.", "hint_word": "open"}'::jsonb, '{"acceptable_answers": ["will open"]}'::jsonb, 0.65, 'C1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000011', 9),
('sentence_completion', '{"sentence": "The dean confirmed that the university ___ launching two new programs next year.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["will be", "is"]}'::jsonb, 0.68, 'C1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000011', 10);

-- Part B: Passage Reconstruction (3, 2 narrative + 1 email)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('passage_reconstruction', '{"passage": "A university noticed declining attendance in one of its large lecture courses. The professor surveyed students and learned the sessions felt too passive. She introduced short group discussions throughout each lecture. Attendance and engagement both improved noticeably over the semester."}'::jsonb, '{"key_points": ["a university noticed declining attendance", "the professor surveyed students about the sessions", "she introduced group discussions", "attendance and engagement improved"]}'::jsonb, 44, 0.55, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000012', 1),
('passage_reconstruction', '{"passage": "A hotel began receiving complaints about slow check-in during busy weekends. Managers reviewed the front-desk process and found only one staff member handled all arrivals. They added a second check-in station on weekends. Guest complaints dropped sharply within a month."}'::jsonb, '{"key_points": ["a hotel received complaints about slow check-in", "only one staff member handled arrivals", "they added a second check-in station", "complaints dropped within a month"]}'::jsonb, 42, 0.56, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000012', 2),
('passage_reconstruction', '{"passage": "Thank you for your recent feedback about the registration process. We understand that the new system caused delays for several students this term, and we sincerely apologize for the inconvenience. We have simplified the steps and added extra support staff for the next registration period."}'::jsonb, '{"key_points": ["thanks for feedback about registration", "apologizes for delays caused by the new system", "the steps have been simplified", "extra support staff were added"]}'::jsonb, 42, 0.56, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000012', 3);

-- Part C: Reading Comprehension (6 = 3 passages x 2 questions each)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('reading_comprehension', '{"passage": "Hotel Occupancy Report: Building A has 80 rooms, 95% occupied this week. Building B has 60 rooms, 70% occupied. Building C has 40 rooms, the lowest occupancy at 50%.", "question": "Which building has the lowest occupancy?", "options": ["Building A", "Building B", "Building C", "None of them"]}'::jsonb, '{"correctIndex": 2}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000013', 1),
('reading_comprehension', '{"passage": "Hotel Occupancy Report: Building A has 80 rooms, 95% occupied this week. Building B has 60 rooms, 70% occupied. Building C has 40 rooms, the lowest occupancy at 50%.", "question": "Which building has the highest occupancy?", "options": ["Building A", "Building B", "Building C", "All equal"]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000013', 2),
('reading_comprehension', '{"passage": "University Policy Excerpt: Students may request a grade appeal within 10 business days of receiving a final grade. Appeals are reviewed by a committee within 30 days.", "question": "How long do students have to request an appeal?", "options": ["5 days", "10 days", "20 days", "30 days"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.42, 'B1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000013', 3),
('reading_comprehension', '{"passage": "University Policy Excerpt: Students may request a grade appeal within 10 business days of receiving a final grade. Appeals are reviewed by a committee within 30 days.", "question": "Who reviews the appeals?", "options": ["The professor alone", "A committee", "The dean alone", "No one"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.44, 'B1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000013', 4),
('reading_comprehension', '{"passage": "Hotel Memo: The new booking system launches next Wednesday. All front-desk staff must complete the training module before then. Supervisors will confirm completion by Tuesday.", "question": "When does the new system launch?", "options": ["This Tuesday", "Next Wednesday", "Next Tuesday", "Immediately"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.45, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000013', 5),
('reading_comprehension', '{"passage": "Hotel Memo: The new booking system launches next Wednesday. All front-desk staff must complete the training module before then. Supervisors will confirm completion by Tuesday.", "question": "Who confirms training completion?", "options": ["HR", "Supervisors", "IT", "No one"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000013', 6);

-- Part D: Email Writing (2)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('email_writing', '{"prompt": "Your university has had an increase in complaints about long advising wait times. Your manager, Dr. Haas, wants ideas for improving the advising process without hiring more staff. Write an email to her suggesting three ways to achieve this. Your suggestions must come from the following three themes: online booking, group advising sessions, extended office hours. You should include all three themes and provide supporting ideas for each of your suggestions."}'::jsonb, null, 0.58, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000014', 1),
('email_writing', '{"prompt": "Your hotel is planning to improve its guest check-in experience. Your manager, Ms. Delacroix, wants ideas for the update. Write an email to her suggesting three priorities for the change. Your suggestions must come from the following three themes: mobile check-in, clearer signage, a dedicated welcome desk. You should include all three themes and provide supporting ideas for each of your suggestions."}'::jsonb, null, 0.58, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000014', 2);

-- Part E: Dictation (8)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('dictation', '{"text": "The hotel just opened."}'::jsonb, '{"exact": "The hotel just opened."}'::jsonb, 4, 0.30, 'A2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000015', 1),
('dictation', '{"text": "She manages the front desk."}'::jsonb, '{"exact": "She manages the front desk."}'::jsonb, 5, 0.34, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000015', 2),
('dictation', '{"text": "They finalized the course schedule yesterday."}'::jsonb, '{"exact": "They finalized the course schedule yesterday."}'::jsonb, 6, 0.40, 'B1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000015', 3),
('dictation', '{"text": "He presented the occupancy report to management."}'::jsonb, '{"exact": "He presented the occupancy report to management."}'::jsonb, 7, 0.45, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000015', 4),
('dictation', '{"text": "The committee approved the revised curriculum this morning."}'::jsonb, '{"exact": "The committee approved the revised curriculum this morning."}'::jsonb, 8, 0.50, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000015', 5),
('dictation', '{"text": "She''s been managing student services for three years."}'::jsonb, '{"exact": "She''s been managing student services for three years."}'::jsonb, 8, 0.55, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000015', 6),
('dictation', '{"text": "The renovation was delayed despite strong support from guests."}'::jsonb, '{"exact": "The renovation was delayed despite strong support from guests."}'::jsonb, 10, 0.62, 'C1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000015', 7),
('dictation', '{"text": "He explained that the new program would be introduced gradually across all campuses."}'::jsonb, '{"exact": "He explained that the new program would be introduced gradually across all campuses."}'::jsonb, 13, 0.68, 'C1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000015', 8);

-- Part F: Response Selection (8)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('response_selection', '{"text": "The guest wants to extend her stay.", "options": ["Sure, let me check availability.", "I enjoy traveling.", "The printer needs toner."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.35, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000016', 1),
('response_selection', '{"text": "We''re fully booked this weekend.", "options": ["Should we open the waitlist?", "That''s a nice color.", "The meeting starts at noon."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.38, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000016', 2),
('response_selection', '{"text": "Can you send me the enrollment numbers by Friday?", "options": ["Yes, I''ll have them ready.", "I don''t like numbers.", "The office is on the third floor."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.42, 'B1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000016', 3),
('response_selection', '{"text": "I think we should hire another advisor.", "options": ["Let''s discuss the budget for that.", "The coffee machine is broken.", "He left early today."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.48, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000016', 4),
('response_selection', '{"text": "The booking system crashed again.", "options": ["Did IT fix it?", "The weather is nice today.", "She''s on vacation next week."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'technology', 'd4000000-0000-4000-8000-000000000016', 5),
('response_selection', '{"text": "A new hotel opened just down the street.", "options": ["We should review our pricing strategy.", "I prefer tea over coffee.", "The parking lot is full."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.55, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000016', 6),
('response_selection', '{"text": "Would you like to lead the new mentoring program?", "options": ["I''d be happy to.", "The copier is out of paper.", "It rained yesterday."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000016', 7),
('response_selection', '{"text": "The guest''s luggage was sent to the wrong room.", "options": ["Let me correct that right away.", "I enjoy long walks.", "The building has five floors."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.58, 'C1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000016', 8);

-- Part G: Passage Comprehension (6 = 2 passages x 3 questions)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('passage_comprehension', '{"story": "A university noticed low attendance at its career fair. The organizer surveyed students afterward and found many did not know it was happening. She launched a targeted email and social media campaign the following year. Attendance nearly doubled.", "question": "What problem did the university notice?"}'::jsonb, '{"acceptable_answers": ["low attendance at the career fair", "low attendance"]}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000017', 1),
('passage_comprehension', '{"story": "A university noticed low attendance at its career fair. The organizer surveyed students afterward and found many did not know it was happening. She launched a targeted email and social media campaign the following year. Attendance nearly doubled.", "question": "What did the survey find?"}'::jsonb, '{"acceptable_answers": ["students did not know about it", "many were unaware"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000017', 2),
('passage_comprehension', '{"story": "A university noticed low attendance at its career fair. The organizer surveyed students afterward and found many did not know it was happening. She launched a targeted email and social media campaign the following year. Attendance nearly doubled.", "question": "What did the organizer do the next year?"}'::jsonb, '{"acceptable_answers": ["launched an email and social media campaign", "a targeted campaign"]}'::jsonb, 0.50, 'B1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000017', 3),
('passage_comprehension', '{"story": "A hotel received several complaints about noise from a nearby renovation. The manager contacted the construction company to adjust working hours. They agreed to avoid early mornings and late evenings. Guest complaints about noise stopped almost entirely.", "question": "What were guests complaining about?"}'::jsonb, '{"acceptable_answers": ["noise from the renovation", "construction noise"]}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000017', 4),
('passage_comprehension', '{"story": "A hotel received several complaints about noise from a nearby renovation. The manager contacted the construction company to adjust working hours. They agreed to avoid early mornings and late evenings. Guest complaints about noise stopped almost entirely.", "question": "What did the manager do?"}'::jsonb, '{"acceptable_answers": ["contacted the construction company", "asked them to adjust hours"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000017', 5),
('passage_comprehension', '{"story": "A hotel received several complaints about noise from a nearby renovation. The manager contacted the construction company to adjust working hours. They agreed to avoid early mornings and late evenings. Guest complaints about noise stopped almost entirely.", "question": "What did the construction company agree to?"}'::jsonb, '{"acceptable_answers": ["avoid early mornings and late evenings", "adjust their working hours"]}'::jsonb, 0.50, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000017', 6);

-- Part H: Repeat (10)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('repeats', '{"text": "The hotel just closed."}'::jsonb, '{"exact": "The hotel just closed."}'::jsonb, 4, 0.28, 'A2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000018', 1),
('repeats', '{"text": "She manages the whole campus."}'::jsonb, '{"exact": "She manages the whole campus."}'::jsonb, 5, 0.32, 'B1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000018', 2),
('repeats', '{"text": "He proposed a new program yesterday."}'::jsonb, '{"exact": "He proposed a new program yesterday."}'::jsonb, 6, 0.36, 'B1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000018', 3),
('repeats', '{"text": "The board approved the renovation plan unanimously."}'::jsonb, '{"exact": "The board approved the renovation plan unanimously."}'::jsonb, 7, 0.40, 'B1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000018', 4),
('repeats', '{"text": "She''s been negotiating this contract for weeks."}'::jsonb, '{"exact": "She''s been negotiating this contract for weeks."}'::jsonb, 7, 0.46, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000018', 5),
('repeats', '{"text": "They decided to delay the opening until spring."}'::jsonb, '{"exact": "They decided to delay the opening until spring."}'::jsonb, 8, 0.50, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000018', 6),
('repeats', '{"text": "He explained that the renovation would take several months."}'::jsonb, '{"exact": "He explained that the renovation would take several months."}'::jsonb, 9, 0.55, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000018', 7),
('repeats', '{"text": "The team worked overtime to meet the guest''s unexpected request."}'::jsonb, '{"exact": "The team worked overtime to meet the guest''s unexpected request."}'::jsonb, 10, 0.60, 'C1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000018', 8),
('repeats', '{"text": "She mentioned that the new program had affected nearly every department on campus."}'::jsonb, '{"exact": "She mentioned that the new program had affected nearly every department on campus."}'::jsonb, 13, 0.66, 'C1', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000018', 9),
('repeats', '{"text": "He explained that the new policy would require every staff member to attend additional training sessions."}'::jsonb, '{"exact": "He explained that the new policy would require every staff member to attend additional training sessions."}'::jsonb, 16, 0.72, 'C1', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000018', 10);

-- Part I: Speaking Situations (2)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('speaking_situations', '{"situation": "A guest complains that their room was not ready at the promised check-in time. You are the front-desk manager. What would you say to the guest?"}'::jsonb, null, 0.55, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-000000000019', 1),
('speaking_situations', '{"situation": "A student emails you asking why their assignment grade was lower than expected. You are their instructor. What would you say in response?"}'::jsonb, null, 0.52, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-000000000019', 2);

-- Part J: Story Retellings (3)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('story_retelling', '{"story": "A hotel concierge noticed guests often asked the same questions about local attractions. Instead of answering each one individually, he created a simple printed guide for the front desk. Guests appreciated having the information readily available. Front-desk calls about local attractions dropped significantly."}'::jsonb, null, 44, 0.52, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-00000000001a', 1),
('story_retelling', '{"story": "A professor noticed that students rarely attended optional office hours. She decided to hold them online instead of in person. Attendance increased immediately, since students could join between other commitments. She now holds most of her office hours online."}'::jsonb, null, 42, 0.54, 'B2', 'approved', 'exam', 'education', 'd4000000-0000-4000-8000-00000000001a', 2),
('story_retelling', '{"story": "A hotel manager noticed that housekeeping sometimes missed rooms during busy checkout days. She introduced a simple checklist system for each floor. Staff began confirming every room before moving to the next. Missed rooms became extremely rare after the change."}'::jsonb, null, 44, 0.53, 'B2', 'approved', 'exam', 'business', 'd4000000-0000-4000-8000-00000000001a', 3);
