-- Practice Tests content: Versant Professional English Test, Set 5 — 58
-- freshly authored items (transportation/airline/general services topics,
-- distinct from Sets 1-4). Completes all 5 sets (290 items) for this
-- product.

-- Part A: Sentence Completion (10)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('sentence_completion', '{"sentence": "The airline''s new boarding system, which took months to test, finally launched ___ all terminals.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["across", "for"]}'::jsonb, 0.45, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000011', 1),
('sentence_completion', '{"sentence": "He has been managing ground operations ___ the airline opened this route last year.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["since"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000011', 2),
('sentence_completion', '{"sentence": "Even with heavy traffic, the shuttle service kept its departures ___ schedule.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["on", "ahead of"]}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000011', 3),
('sentence_completion', '{"sentence": "Safety regulations require that all vehicles ___ inspected before each shift.", "hint_word": "inspect"}'::jsonb, '{"acceptable_answers": ["be inspected"]}'::jsonb, 0.55, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000011', 4),
('sentence_completion', '{"sentence": "She apologized to the passengers ___ the delay caused by the mechanical issue.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["for"]}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000011', 5),
('sentence_completion', '{"sentence": "Several routes were proposed, but only one ___ be approved this quarter.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["will"]}'::jsonb, 0.58, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000011', 6),
('sentence_completion', '{"sentence": "Despite the storm, the airport resumed normal operations ___ the end of the day.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["by"]}'::jsonb, 0.60, 'C1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000011', 7),
('sentence_completion', '{"sentence": "The consultant recommended restructuring the boarding process ___ reducing delays.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["to"]}'::jsonb, 0.62, 'C1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000011', 8),
('sentence_completion', '{"sentence": "If maintenance finishes the inspection today, the aircraft ___ depart as scheduled.", "hint_word": "depart"}'::jsonb, '{"acceptable_answers": ["will depart"]}'::jsonb, 0.65, 'C1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000011', 9),
('sentence_completion', '{"sentence": "The director confirmed that the airline ___ adding two new routes next year.", "hint_word": ""}'::jsonb, '{"acceptable_answers": ["will be", "is"]}'::jsonb, 0.68, 'C1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000011', 10);

-- Part B: Passage Reconstruction (3, 2 narrative + 1 email)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('passage_reconstruction', '{"passage": "An airline noticed recurring delays at one of its busiest gates. Ground staff reviewed the boarding process and found it was too slow for large aircraft. They introduced zone-based boarding to speed things up. Average boarding time dropped by several minutes within weeks."}'::jsonb, '{"key_points": ["an airline noticed recurring delays at a gate", "staff found boarding was too slow", "they introduced zone-based boarding", "boarding time dropped within weeks"]}'::jsonb, 45, 0.55, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000012', 1),
('passage_reconstruction', '{"passage": "A bus company kept receiving complaints about overcrowded routes during rush hour. Managers reviewed ridership data and found one route far exceeded capacity. They added extra buses during peak times only. Passenger complaints about that route decreased significantly."}'::jsonb, '{"key_points": ["a bus company received complaints about overcrowding", "one route exceeded capacity", "they added extra buses at peak times", "complaints decreased significantly"]}'::jsonb, 41, 0.56, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000012', 2),
('passage_reconstruction', '{"passage": "Thank you for your patience regarding the recent flight delay. We understand this disrupted your travel plans, and we sincerely apologize for the inconvenience. As a gesture of goodwill, we have applied a travel credit to your account for use on a future booking."}'::jsonb, '{"key_points": ["thanks for patience with the flight delay", "apologizes for the disruption", "a travel credit was applied", "it can be used on a future booking"]}'::jsonb, 42, 0.56, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000012', 3);

-- Part C: Reading Comprehension (6 = 3 passages x 2 questions each)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('reading_comprehension', '{"passage": "Flight Status Board: Flight 204 departs 8am, on time. Flight 310 departs 9:15am, delayed 45 minutes. Flight 512 departs 11am, cancelled due to weather.", "question": "Which flight is delayed?", "options": ["Flight 204", "Flight 310", "Flight 512", "None of them"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000013', 1),
('reading_comprehension', '{"passage": "Flight Status Board: Flight 204 departs 8am, on time. Flight 310 departs 9:15am, delayed 45 minutes. Flight 512 departs 11am, cancelled due to weather.", "question": "Which flight is cancelled?", "options": ["Flight 204", "Flight 310", "Flight 512", "All of them"]}'::jsonb, '{"correctIndex": 2}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000013', 2),
('reading_comprehension', '{"passage": "Airline Policy Excerpt: Passengers may check two bags free of charge on international flights. A third bag incurs a fee of $75. Oversized bags are subject to an additional handling charge.", "question": "How many bags can be checked free on international flights?", "options": ["One", "Two", "Three", "Four"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.42, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000013', 3),
('reading_comprehension', '{"passage": "Airline Policy Excerpt: Passengers may check two bags free of charge on international flights. A third bag incurs a fee of $75. Oversized bags are subject to an additional handling charge.", "question": "What happens with oversized bags?", "options": ["They are refused", "An additional charge applies", "They travel free", "They are lost automatically"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.44, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000013', 4),
('reading_comprehension', '{"passage": "Transit Memo: The new fare payment system launches next Monday. All drivers must complete the training module before then. Supervisors will confirm completion by Friday.", "question": "When does the new system launch?", "options": ["This Friday", "Next Monday", "Next Friday", "Immediately"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.45, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000013', 5),
('reading_comprehension', '{"passage": "Transit Memo: The new fare payment system launches next Monday. All drivers must complete the training module before then. Supervisors will confirm completion by Friday.", "question": "Who confirms training completion?", "options": ["HR", "Supervisors", "IT", "No one"]}'::jsonb, '{"correctIndex": 1}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000013', 6);

-- Part D: Email Writing (2)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('email_writing', '{"prompt": "Your airline has had an increase in complaints about boarding delays. Your manager, Mr. Fontaine, wants ideas for improving the boarding process without adding staff. Write an email to him suggesting three ways to achieve this. Your suggestions must come from the following three themes: zone-based boarding, clearer gate announcements, a dedicated priority lane. You should include all three themes and provide supporting ideas for each of your suggestions."}'::jsonb, null, 0.58, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000014', 1),
('email_writing', '{"prompt": "Your transit company is planning to improve its customer communication during delays. Your manager, Ms. Abara, wants ideas for the update. Write an email to her suggesting three priorities for the change. Your suggestions must come from the following three themes: real-time app alerts, clearer station announcements, a customer support hotline. You should include all three themes and provide supporting ideas for each of your suggestions."}'::jsonb, null, 0.58, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000014', 2);

-- Part E: Dictation (8)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('dictation', '{"text": "The flight just landed."}'::jsonb, '{"exact": "The flight just landed."}'::jsonb, 4, 0.30, 'A2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000015', 1),
('dictation', '{"text": "She manages ground operations."}'::jsonb, '{"exact": "She manages ground operations."}'::jsonb, 4, 0.34, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000015', 2),
('dictation', '{"text": "They finalized the new route yesterday."}'::jsonb, '{"exact": "They finalized the new route yesterday."}'::jsonb, 6, 0.40, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000015', 3),
('dictation', '{"text": "He presented the safety report to management."}'::jsonb, '{"exact": "He presented the safety report to management."}'::jsonb, 7, 0.45, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000015', 4),
('dictation', '{"text": "The committee approved the revised flight schedule today."}'::jsonb, '{"exact": "The committee approved the revised flight schedule today."}'::jsonb, 8, 0.50, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000015', 5),
('dictation', '{"text": "She''s been overseeing airport operations for three years."}'::jsonb, '{"exact": "She''s been overseeing airport operations for three years."}'::jsonb, 8, 0.55, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000015', 6),
('dictation', '{"text": "The flight was delayed despite the crew''s best efforts."}'::jsonb, '{"exact": "The flight was delayed despite the crew''s best efforts."}'::jsonb, 10, 0.62, 'C1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000015', 7),
('dictation', '{"text": "He explained that the new boarding process would be tested gradually across hubs."}'::jsonb, '{"exact": "He explained that the new boarding process would be tested gradually across hubs."}'::jsonb, 13, 0.68, 'C1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000015', 8);

-- Part F: Response Selection (8)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('response_selection', '{"text": "The passenger wants to change her seat.", "options": ["Sure, let me check availability.", "I enjoy flying.", "The printer needs toner."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.35, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000016', 1),
('response_selection', '{"text": "We''re fully booked on that route.", "options": ["Should we open a waitlist?", "That''s a nice color.", "The meeting starts at noon."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.38, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000016', 2),
('response_selection', '{"text": "Can you send me the maintenance log by Friday?", "options": ["Yes, I''ll have it ready.", "I don''t like logs.", "The office is on the third floor."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.42, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000016', 3),
('response_selection', '{"text": "I think we should add another route.", "options": ["Let''s discuss the budget for that.", "The coffee machine is broken.", "He left early today."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.48, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000016', 4),
('response_selection', '{"text": "The booking system crashed again.", "options": ["Did IT fix it?", "The weather is nice today.", "She''s on vacation next week."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.50, 'B2', 'approved', 'exam', 'technology', 'd5000000-0000-4000-8000-000000000016', 5),
('response_selection', '{"text": "A competing airline just launched a similar route.", "options": ["We should review our pricing strategy.", "I prefer tea over coffee.", "The parking lot is full."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.55, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000016', 6),
('response_selection', '{"text": "Would you like to lead the new safety initiative?", "options": ["I''d be happy to.", "The copier is out of paper.", "It rained yesterday."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.52, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000016', 7),
('response_selection', '{"text": "The passenger''s luggage was sent to the wrong city.", "options": ["Let me correct that right away.", "I enjoy long walks.", "The building has five floors."]}'::jsonb, '{"correctIndex": 0}'::jsonb, 0.58, 'C1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000016', 8);

-- Part G: Passage Comprehension (6 = 2 passages x 3 questions)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('passage_comprehension', '{"story": "An airline noticed frequent complaints about lost luggage on one route. Staff traced the issue to a sorting error at a connecting hub. They retrained the baggage handling team at that hub. Lost luggage reports on that route dropped sharply.", "question": "What complaints did the airline notice?"}'::jsonb, '{"acceptable_answers": ["complaints about lost luggage", "lost luggage"]}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000017', 1),
('passage_comprehension', '{"story": "An airline noticed frequent complaints about lost luggage on one route. Staff traced the issue to a sorting error at a connecting hub. They retrained the baggage handling team at that hub. Lost luggage reports on that route dropped sharply.", "question": "What caused the issue?"}'::jsonb, '{"acceptable_answers": ["a sorting error at a hub", "a sorting error"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000017', 2),
('passage_comprehension', '{"story": "An airline noticed frequent complaints about lost luggage on one route. Staff traced the issue to a sorting error at a connecting hub. They retrained the baggage handling team at that hub. Lost luggage reports on that route dropped sharply.", "question": "What did they do about it?"}'::jsonb, '{"acceptable_answers": ["retrained the baggage handling team", "retrained staff at the hub"]}'::jsonb, 0.50, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000017', 3),
('passage_comprehension', '{"story": "A transit agency kept receiving complaints about unreliable bus arrival times. Engineers discovered the tracking app used outdated GPS data. They upgraded the system to use real-time location data. Complaints about arrival times dropped significantly afterward.", "question": "What complaints was the agency receiving?"}'::jsonb, '{"acceptable_answers": ["unreliable bus arrival times", "unreliable arrival times"]}'::jsonb, 0.46, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000017', 4),
('passage_comprehension', '{"story": "A transit agency kept receiving complaints about unreliable bus arrival times. Engineers discovered the tracking app used outdated GPS data. They upgraded the system to use real-time location data. Complaints about arrival times dropped significantly afterward.", "question": "What did engineers discover?"}'::jsonb, '{"acceptable_answers": ["the app used outdated GPS data", "outdated GPS data"]}'::jsonb, 0.48, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000017', 5),
('passage_comprehension', '{"story": "A transit agency kept receiving complaints about unreliable bus arrival times. Engineers discovered the tracking app used outdated GPS data. They upgraded the system to use real-time location data. Complaints about arrival times dropped significantly afterward.", "question": "What did they upgrade the system to use?"}'::jsonb, '{"acceptable_answers": ["real-time location data", "real-time data"]}'::jsonb, 0.50, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000017', 6);

-- Part H: Repeat (10)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('repeats', '{"text": "The flight just departed."}'::jsonb, '{"exact": "The flight just departed."}'::jsonb, 4, 0.28, 'A2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000018', 1),
('repeats', '{"text": "She manages ground control."}'::jsonb, '{"exact": "She manages ground control."}'::jsonb, 4, 0.32, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000018', 2),
('repeats', '{"text": "He proposed a new route yesterday."}'::jsonb, '{"exact": "He proposed a new route yesterday."}'::jsonb, 6, 0.36, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000018', 3),
('repeats', '{"text": "The board approved the new schedule unanimously."}'::jsonb, '{"exact": "The board approved the new schedule unanimously."}'::jsonb, 7, 0.40, 'B1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000018', 4),
('repeats', '{"text": "She''s been negotiating this route contract for weeks."}'::jsonb, '{"exact": "She''s been negotiating this route contract for weeks."}'::jsonb, 8, 0.46, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000018', 5),
('repeats', '{"text": "They decided to delay the launch until spring."}'::jsonb, '{"exact": "They decided to delay the launch until spring."}'::jsonb, 8, 0.50, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000018', 6),
('repeats', '{"text": "He explained that the upgrade would take several months."}'::jsonb, '{"exact": "He explained that the upgrade would take several months."}'::jsonb, 9, 0.55, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000018', 7),
('repeats', '{"text": "The crew worked overtime to meet the passengers'' unexpected needs."}'::jsonb, '{"exact": "The crew worked overtime to meet the passengers'' unexpected needs."}'::jsonb, 10, 0.60, 'C1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000018', 8),
('repeats', '{"text": "She mentioned that the new system had affected nearly every hub in the network."}'::jsonb, '{"exact": "She mentioned that the new system had affected nearly every hub in the network."}'::jsonb, 14, 0.66, 'C1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000018', 9),
('repeats', '{"text": "He explained that the new policy would require every pilot to attend additional training sessions."}'::jsonb, '{"exact": "He explained that the new policy would require every pilot to attend additional training sessions."}'::jsonb, 15, 0.72, 'C1', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000018', 10);

-- Part I: Speaking Situations (2)
INSERT INTO items (item_type_id, content, answer_set, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('speaking_situations', '{"situation": "A passenger missed their connecting flight because of a delay on your airline. You are the gate agent helping them. What would you say to the passenger?"}'::jsonb, null, 0.55, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000019', 1),
('speaking_situations', '{"situation": "A coworker on your shift keeps arriving late, putting extra pressure on the team. You decide to address it with him directly. What would you say?"}'::jsonb, null, 0.52, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-000000000019', 2);

-- Part J: Story Retellings (3)
INSERT INTO items (item_type_id, content, answer_set, word_count, difficulty, cefr_level, status, pool, topic, exam_part_id, exam_order) VALUES
('story_retelling', '{"story": "A gate agent noticed a family about to miss their connecting flight due to a terminal change. Instead of letting them struggle, she personally guided them through the shortcut route. They made the flight with only minutes to spare. The family thanked her sincerely before boarding."}'::jsonb, null, 47, 0.52, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-00000000001a', 1),
('story_retelling', '{"story": "A transit driver noticed a regular passenger seemed unusually distressed one morning. He gently asked if everything was alright. She explained she was running late for an important interview. He radioed ahead so she could catch a connecting bus immediately on arrival."}'::jsonb, null, 45, 0.54, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-00000000001a', 2),
('story_retelling', '{"story": "An airport security team noticed long lines forming every morning during peak travel hours. Instead of simply adding more staff, they analyzed the checkpoint layout and found a bottleneck at bag inspection. Rearranging the stations reduced average wait times considerably."}'::jsonb, null, 44, 0.53, 'B2', 'approved', 'exam', 'business', 'd5000000-0000-4000-8000-00000000001a', 3);
