-- B2 units/sets for all 19 item types: 3 sets per type, 5 questions per
-- set, 15 items per type (285 total). Calibration continues the existing
-- A1/A2/B1 bands (B1 0.45-0.58): B2 0.55-0.68.
BEGIN;

-- ===================== reading =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('reading', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('reading', '{"text": "Although the merger was announced months ago, employees are still uncertain about how it will affect their roles."}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('reading', '{"text": "The committee postponed its decision after several members raised concerns about the proposal''s long-term costs."}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('reading', '{"text": "Despite the setbacks, the research team remained confident that the project would eventually succeed."}', 0.58, 'B2', 'approved', 'manual', 'education', 'practice', :'s1_id', 3),
('reading', '{"text": "Customers were frustrated when the delivery was delayed for the third time this month."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('reading', '{"text": "The city council is considering a proposal to reduce traffic congestion in the downtown area."}', 0.57, 'B2', 'approved', 'manual', 'community', 'practice', :'s1_id', 5),
('reading', '{"text": "It took the negotiators several rounds of discussion before they finally reached an agreement."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('reading', '{"text": "Many employees were surprised to learn that the company planned to relocate its headquarters next year."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('reading', '{"text": "The professor explained that the experiment''s results contradicted much of the earlier research."}', 0.62, 'B2', 'approved', 'manual', 'education', 'practice', :'s2_id', 3),
('reading', '{"text": "Although demand has grown steadily, the company has been reluctant to expand its production capacity."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('reading', '{"text": "She was hesitant to accept the promotion because it would require relocating to another country."}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('reading', '{"text": "The budget committee ultimately rejected the proposal, citing concerns about its feasibility."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('reading', '{"text": "Critics argue that the new policy fails to address the underlying causes of the problem."}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('reading', '{"text": "Despite years of planning, the construction project encountered unexpected regulatory obstacles."}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('reading', '{"text": "The researchers acknowledged that their findings, while promising, required further validation."}', 0.65, 'B2', 'approved', 'manual', 'education', 'practice', :'s3_id', 4),
('reading', '{"text": "The board remains divided over whether to pursue the acquisition despite its potential benefits."}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== reading_selective =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('reading_selective', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('reading_selective', '{"text": "Due to unexpected demand, the conference has been moved to a larger venue across town.", "question": "Why was the conference moved?"}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["unexpected demand", "because of demand"]}', :'s1_id', 1),
('reading_selective', '{"text": "The contract will automatically renew unless either party gives written notice thirty days in advance.", "question": "How much notice is required to cancel?"}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["thirty days", "30 days"]}', :'s1_id', 2),
('reading_selective', '{"text": "The warranty covers manufacturing defects but does not include damage caused by improper use.", "question": "What does the warranty not cover?"}', 0.58, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["damage from improper use", "improper use"]}', :'s1_id', 3),
('reading_selective', '{"text": "Applicants must submit their portfolios by Friday to be considered for the spring intake.", "question": "What is the deadline?"}', 0.56, 'B2', 'approved', 'manual', 'education', 'practice', '{"acceptable_answers": ["friday"]}', :'s1_id', 4),
('reading_selective', '{"text": "The survey revealed that most employees preferred flexible hours over a higher salary.", "question": "What did most employees prefer?"}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["flexible hours"]}', :'s1_id', 5),
('reading_selective', '{"text": "Although the flight was delayed by two hours, passengers were offered meal vouchers as compensation.", "question": "What were passengers offered?"}', 0.60, 'B2', 'approved', 'manual', 'travel', 'practice', '{"acceptable_answers": ["meal vouchers"]}', :'s2_id', 1),
('reading_selective', '{"text": "The museum''s new exhibit focuses on sustainable architecture from the past two decades.", "question": "What does the exhibit focus on?"}', 0.61, 'B2', 'approved', 'manual', 'culture', 'practice', '{"acceptable_answers": ["sustainable architecture"]}', :'s2_id', 2),
('reading_selective', '{"text": "The company reported a slight decline in revenue, attributing it to rising material costs.", "question": "What caused the revenue decline?"}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["rising material costs", "material costs"]}', :'s2_id', 3),
('reading_selective', '{"text": "Residents were asked to conserve water after the reservoir levels dropped below normal.", "question": "Why were residents asked to conserve water?"}', 0.60, 'B2', 'approved', 'manual', 'community', 'practice', '{"acceptable_answers": ["low reservoir levels", "reservoir levels dropped"]}', :'s2_id', 4),
('reading_selective', '{"text": "The new software update improves battery life but removes an older, rarely used feature.", "question": "What does the update improve?"}', 0.62, 'B2', 'approved', 'manual', 'technology', 'practice', '{"acceptable_answers": ["battery life"]}', :'s2_id', 5),
('reading_selective', '{"text": "Despite initial resistance, most staff eventually adapted well to the new scheduling system.", "question": "How did staff eventually respond?"}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["adapted well", "they adapted"]}', :'s3_id', 1),
('reading_selective', '{"text": "The city plans to plant two thousand trees over the next five years as part of a green initiative.", "question": "How many trees will be planted?"}', 0.66, 'B2', 'approved', 'manual', 'environment', 'practice', '{"acceptable_answers": ["two thousand", "2000"]}', :'s3_id', 2),
('reading_selective', '{"text": "The report concluded that remote work had little measurable effect on overall productivity.", "question": "What did the report conclude?"}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["little effect on productivity", "no real effect"]}', :'s3_id', 3),
('reading_selective', '{"text": "The airline announced it would add three new routes beginning next spring.", "question": "How many new routes were announced?"}', 0.65, 'B2', 'approved', 'manual', 'travel', 'practice', '{"acceptable_answers": ["three", "3"]}', :'s3_id', 4),
('reading_selective', '{"text": "Volunteers collected over five hundred kilograms of litter during the weekend cleanup event.", "question": "How much litter was collected?"}', 0.68, 'B2', 'approved', 'manual', 'environment', 'practice', '{"acceptable_answers": ["five hundred kilograms", "500 kilograms", "500 kg"]}', :'s3_id', 5);

-- ===================== repeats =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('repeats', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('repeats', '{"text": "She mentioned that the warehouse manager had already reviewed the inventory."}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('repeats', '{"text": "He wondered whether the negotiations would be completed by Friday."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('repeats', '{"text": "They''re trying to convince the board to approve the new policy."}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('repeats', '{"text": "I wasn''t sure which supplier offered the best overall value."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('repeats', '{"text": "She explained that the audit had uncovered several minor discrepancies."}', 0.58, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('repeats', '{"text": "He''s hoping the merger will be finalized before the end of the year."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('repeats', '{"text": "They decided to postpone the product launch until next quarter."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('repeats', '{"text": "She wanted to know whether the training sessions were mandatory."}', 0.60, 'B2', 'approved', 'manual', 'education', 'practice', :'s2_id', 3),
('repeats', '{"text": "He pointed out that the report lacked sufficient supporting evidence."}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('repeats', '{"text": "They''re planning to restructure the department to improve efficiency."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('repeats', '{"text": "She admitted that she hadn''t anticipated such a strong reaction."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('repeats', '{"text": "He insisted that the deadline could still be met if resources were reallocated."}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('repeats', '{"text": "They''re concerned that the new regulations might affect profitability."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('repeats', '{"text": "She clarified that the budget cuts would not impact staff salaries."}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('repeats', '{"text": "He acknowledged that the initial plan needed significant revisions."}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== short_answer =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('short_answer', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('short_answer', '{"question": "Why might a company choose to outsource part of its production?"}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('short_answer', '{"question": "What are the risks of relying too heavily on a single supplier?"}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('short_answer', '{"question": "Why do some employees resist organizational change?"}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('short_answer', '{"question": "What factors influence a customer''s brand loyalty?"}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('short_answer', '{"question": "Why is work-life balance important for long-term productivity?"}', 0.58, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('short_answer', '{"question": "What challenges arise when managing a remote team?"}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('short_answer', '{"question": "Why might a business invest in employee training programs?"}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('short_answer', '{"question": "What are common causes of miscommunication in the workplace?"}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('short_answer', '{"question": "Why do companies conduct market research before launching a product?"}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('short_answer', '{"question": "What strategies can reduce employee turnover?"}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('short_answer', '{"question": "Why is adaptability valued in fast-changing industries?"}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('short_answer', '{"question": "What are the benefits of diversifying a company''s client base?"}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('short_answer', '{"question": "Why might a merger fail despite careful planning?"}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('short_answer', '{"question": "What role does leadership play during organizational crises?"}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('short_answer', '{"question": "Why do businesses conduct regular performance reviews?"}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== sentence_builds =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('sentence_builds', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('sentence_builds', '{"groups": ["despite the delay", "the project", "was completed", "on budget"]}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "Despite the delay, the project was completed on budget.", "alternates": []}', :'s1_id', 1),
('sentence_builds', '{"groups": ["before approving the loan", "the bank", "reviewed", "his credit history"]}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "Before approving the loan, the bank reviewed his credit history.", "alternates": []}', :'s1_id', 2),
('sentence_builds', '{"groups": ["the committee", "will announce", "its decision", "by the end of the week"]}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "The committee will announce its decision by the end of the week.", "alternates": []}', :'s1_id', 3),
('sentence_builds', '{"groups": ["having reviewed the proposal", "the investors", "decided", "to withdraw their support"]}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "Having reviewed the proposal, the investors decided to withdraw their support.", "alternates": []}', :'s1_id', 4),
('sentence_builds', '{"groups": ["the new regulation", "requires", "all vehicles", "to pass an emissions test"]}', 0.58, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "The new regulation requires all vehicles to pass an emissions test.", "alternates": []}', :'s1_id', 5),
('sentence_builds', '{"groups": ["unless the weather improves", "the flight", "will likely be", "delayed"]}', 0.60, 'B2', 'approved', 'manual', 'travel', 'practice', '{"correct": "Unless the weather improves, the flight will likely be delayed.", "alternates": []}', :'s2_id', 1),
('sentence_builds', '{"groups": ["the manager", "admitted", "that the targets", "were unrealistic"]}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "The manager admitted that the targets were unrealistic.", "alternates": []}', :'s2_id', 2),
('sentence_builds', '{"groups": ["after much deliberation", "the jury", "reached", "a unanimous verdict"]}', 0.62, 'B2', 'approved', 'manual', 'general', 'practice', '{"correct": "After much deliberation, the jury reached a unanimous verdict.", "alternates": []}', :'s2_id', 3),
('sentence_builds', '{"groups": ["the researchers", "were surprised", "by how quickly", "the results changed"]}', 0.60, 'B2', 'approved', 'manual', 'education', 'practice', '{"correct": "The researchers were surprised by how quickly the results changed.", "alternates": []}', :'s2_id', 4),
('sentence_builds', '{"groups": ["should the contract", "fall through", "we will need", "an alternative plan"]}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "Should the contract fall through, we will need an alternative plan.", "alternates": []}', :'s2_id', 5),
('sentence_builds', '{"groups": ["given the circumstances", "the board", "had little choice", "but to intervene"]}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "Given the circumstances, the board had little choice but to intervene.", "alternates": []}', :'s3_id', 1),
('sentence_builds', '{"groups": ["the proposal", "was rejected", "on the grounds", "that it was too costly"]}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "The proposal was rejected on the grounds that it was too costly.", "alternates": []}', :'s3_id', 2),
('sentence_builds', '{"groups": ["not only did sales rise", "but customer satisfaction", "also", "improved"]}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "Not only did sales rise, but customer satisfaction also improved.", "alternates": []}', :'s3_id', 3),
('sentence_builds', '{"groups": ["the engineer", "pointed out", "that the design flaw", "could be fixed easily"]}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "The engineer pointed out that the design flaw could be fixed easily.", "alternates": []}', :'s3_id', 4),
('sentence_builds', '{"groups": ["had the company acted sooner", "the losses", "could have been", "avoided"]}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', '{"correct": "Had the company acted sooner, the losses could have been avoided.", "alternates": []}', :'s3_id', 5);

-- ===================== conversations =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('conversations', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('conversations', '{"dialogue": "A: The client pushed back the deadline. B: That''s a relief. A: Yes, it gives us two more weeks.", "question": "How much extra time do they have?"}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["two more weeks", "2 weeks"]}', :'s1_id', 1),
('conversations', '{"dialogue": "A: Did the board approve the budget? B: Not entirely. A: What did they change?", "question": "Did the board fully approve the budget?"}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["no", "not entirely"]}', :'s1_id', 2),
('conversations', '{"dialogue": "A: Our main competitor just lowered their prices. B: By how much? A: About fifteen percent.", "question": "By how much did the competitor lower prices?"}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["fifteen percent", "15 percent", "15%"]}', :'s1_id', 3),
('conversations', '{"dialogue": "A: The supplier missed another shipment. B: This is the third time. A: We need to find an alternative.", "question": "How many times has the supplier missed a shipment?"}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["three times", "3 times", "the third time"]}', :'s1_id', 4),
('conversations', '{"dialogue": "A: I heard the merger fell through. B: Really? What happened? A: The two sides couldn''t agree on valuation.", "question": "Why did the merger fall through?"}', 0.58, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["disagreement over valuation", "they could not agree on valuation"]}', :'s1_id', 5),
('conversations', '{"dialogue": "A: The survey results came back. B: And? A: Customer satisfaction dropped slightly this quarter.", "question": "What happened to customer satisfaction?"}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["it dropped slightly", "dropped"]}', :'s2_id', 1),
('conversations', '{"dialogue": "A: We''re over capacity at the warehouse. B: Since when? A: Since the new product line launched.", "question": "Since when has the warehouse been over capacity?"}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["since the new product line launched", "since the launch"]}', :'s2_id', 2),
('conversations', '{"dialogue": "A: The regulator flagged our report. B: For what reason? A: A few figures didn''t match last quarter''s filing.", "question": "Why was the report flagged?"}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["figures did not match", "mismatched figures"]}', :'s2_id', 3),
('conversations', '{"dialogue": "A: Did the new hire start yet? B: Yes, last Monday. A: How''s it going so far?", "question": "When did the new hire start?"}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["last Monday", "Monday"]}', :'s2_id', 4),
('conversations', '{"dialogue": "A: We lost the Henderson account. B: That''s a big loss. A: Yes, it was almost a third of our revenue.", "question": "How much of their revenue did the account represent?"}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["almost a third", "about one third"]}', :'s2_id', 5),
('conversations', '{"dialogue": "A: The acquisition talks stalled. B: Over what? A: Mostly disagreements about leadership roles.", "question": "What caused the talks to stall?"}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["disagreements about leadership roles", "leadership disagreements"]}', :'s3_id', 1),
('conversations', '{"dialogue": "A: The factory passed the inspection. B: With any issues? A: Just a couple of minor recommendations.", "question": "What did the inspection find?"}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["minor recommendations", "a couple of minor issues"]}', :'s3_id', 2),
('conversations', '{"dialogue": "A: The client wants a full refund. B: Did we agree? A: Only a partial one, after negotiation.", "question": "What was finally agreed?"}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["a partial refund", "partial refund"]}', :'s3_id', 3),
('conversations', '{"dialogue": "A: Our forecast missed by a wide margin. B: How wide? A: Almost twenty percent under projections.", "question": "By how much did the forecast miss?"}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["almost twenty percent", "20 percent", "20%"]}', :'s3_id', 4),
('conversations', '{"dialogue": "A: The policy change caused backlash. B: From whom? A: Mainly from long-term customers.", "question": "Who reacted most to the policy change?"}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["long-term customers", "long term customers"]}', :'s3_id', 5);

-- ===================== sentence_completion =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('sentence_completion', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('sentence_completion', '{"sentence": "The proposal was rejected ___ of concerns about its cost.", "hint_word": ""}', 0.55, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["because", "on account"]}', :'s1_id', 1),
('sentence_completion', '{"sentence": "___ the delay, the project was delivered on time.", "hint_word": ""}', 0.56, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["despite", "notwithstanding"]}', :'s1_id', 2),
('sentence_completion', '{"sentence": "The report ___ reviewed before it reaches the board.", "hint_word": "must"}', 0.57, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["must be"]}', :'s1_id', 3),
('sentence_completion', '{"sentence": "She''s the analyst ___ findings changed the whole strategy.", "hint_word": ""}', 0.56, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["whose"]}', :'s1_id', 4),
('sentence_completion', '{"sentence": "Had the team acted sooner, the issue ___ been resolved.", "hint_word": "have"}', 0.58, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["would have"]}', :'s1_id', 5),
('sentence_completion', '{"sentence": "The policy comes into effect ___ January first.", "hint_word": ""}', 0.60, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["on"]}', :'s2_id', 1),
('sentence_completion', '{"sentence": "If the merger goes through, both companies ___ benefit significantly.", "hint_word": "benefit"}', 0.61, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["will benefit"]}', :'s2_id', 2),
('sentence_completion', '{"sentence": "The contract ___ by both parties before the deadline.", "hint_word": "sign"}', 0.60, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["was signed"]}', :'s2_id', 3),
('sentence_completion', '{"sentence": "She''s not used to ___ decisions under such pressure.", "hint_word": "make"}', 0.62, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["making"]}', :'s2_id', 4),
('sentence_completion', '{"sentence": "Neither the manager nor the staff ___ informed of the change.", "hint_word": "be"}', 0.61, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["were", "was"]}', :'s2_id', 5),
('sentence_completion', '{"sentence": "By the time the audit concluded, the errors ___ already been corrected.", "hint_word": "have"}', 0.65, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["had"]}', :'s3_id', 1),
('sentence_completion', '{"sentence": "The committee is divided ___ whether to approve the plan.", "hint_word": ""}', 0.66, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["over", "on"]}', :'s3_id', 2),
('sentence_completion', '{"sentence": "Were the budget approved, the project ___ begin immediately.", "hint_word": "begin"}', 0.67, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["would begin"]}', :'s3_id', 3),
('sentence_completion', '{"sentence": "The CEO is known ___ making bold, risky decisions.", "hint_word": ""}', 0.65, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["for"]}', :'s3_id', 4),
('sentence_completion', '{"sentence": "The new hires ___ expected to complete orientation within a week.", "hint_word": "expect"}', 0.68, 'B2', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["are"]}', :'s3_id', 5);

-- ===================== dictation =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('dictation', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('dictation', '{"text": "The board postponed its decision until next week."}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('dictation', '{"text": "She''s been overseeing the project since it began."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('dictation', '{"text": "The merger talks collapsed after months of negotiation."}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('dictation', '{"text": "He explained that the budget cuts were unavoidable."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('dictation', '{"text": "They decided to relocate the office closer to downtown."}', 0.58, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('dictation', '{"text": "The supplier agreed to expedite the delayed shipment."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('dictation', '{"text": "She mentioned that the proposal needed further revisions."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('dictation', '{"text": "The regulator requested additional documentation before approval."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('dictation', '{"text": "He acknowledged that the forecast had been overly optimistic."}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('dictation', '{"text": "They''re negotiating a new contract with the main supplier."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('dictation', '{"text": "The committee ultimately rejected the proposal despite strong support."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('dictation', '{"text": "She clarified that the restructuring would not affect salaries."}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('dictation', '{"text": "The audit uncovered several discrepancies in the quarterly report."}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('dictation', '{"text": "He insisted the deadline could still be met with adjustments."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('dictation', '{"text": "They''re concerned the new regulations may affect profitability."}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== passage_reconstruction =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('passage_reconstruction', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('passage_reconstruction', '{"passage": "The company reported lower earnings this quarter, citing higher raw material costs and weaker consumer demand."}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["lower earnings", "higher material costs", "weaker demand"]}', :'s1_id', 1),
('passage_reconstruction', '{"passage": "After reviewing the feedback, the design team decided to simplify the interface to make it more intuitive for new users."}', 0.56, 'B2', 'approved', 'manual', 'technology', 'practice', '{"key_points": ["reviewed feedback", "simplified the interface", "more intuitive for new users"]}', :'s1_id', 2),
('passage_reconstruction', '{"passage": "The city council approved a plan to expand the public bus network, despite objections from local residents concerned about noise."}', 0.57, 'B2', 'approved', 'manual', 'community', 'practice', '{"key_points": ["council approved expanding bus network", "residents objected over noise"]}', :'s1_id', 3),
('passage_reconstruction', '{"passage": "Researchers found that the new treatment reduced symptoms significantly, though more long-term studies are still needed."}', 0.56, 'B2', 'approved', 'manual', 'education', 'practice', '{"key_points": ["treatment reduced symptoms significantly", "more long-term studies needed"]}', :'s1_id', 4),
('passage_reconstruction', '{"passage": "The airline apologized for the delay, explaining that a mechanical issue had been discovered during a routine check."}', 0.58, 'B2', 'approved', 'manual', 'travel', 'practice', '{"key_points": ["airline apologized for the delay", "mechanical issue found during a check"]}', :'s1_id', 5),
('passage_reconstruction', '{"passage": "Despite initial skepticism, investors eventually backed the startup after seeing strong early user growth figures."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["investors were initially skeptical", "backed the startup after strong growth"]}', :'s2_id', 1),
('passage_reconstruction', '{"passage": "The factory implemented new safety protocols after an inspection revealed several outdated procedures."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["new safety protocols implemented", "inspection found outdated procedures"]}', :'s2_id', 2),
('passage_reconstruction', '{"passage": "The university announced a partnership with a local hospital to expand research opportunities for medical students."}', 0.62, 'B2', 'approved', 'manual', 'education', 'practice', '{"key_points": ["university partnered with a hospital", "expands research for medical students"]}', :'s2_id', 3),
('passage_reconstruction', '{"passage": "The retailer''s online sales surged after it introduced a same-day delivery option in major cities."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["online sales surged", "introduced same-day delivery in major cities"]}', :'s2_id', 4),
('passage_reconstruction', '{"passage": "The engineer proposed a redesign that would reduce production costs without compromising the product''s durability."}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["engineer proposed a redesign", "reduces costs without hurting durability"]}', :'s2_id', 5),
('passage_reconstruction', '{"passage": "The negotiations stalled when both parties failed to agree on how to divide the shared intellectual property."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["negotiations stalled", "disagreement over dividing intellectual property"]}', :'s3_id', 1),
('passage_reconstruction', '{"passage": "The agency revised its forecast downward after unexpected weather patterns disrupted crop yields across the region."}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["agency revised forecast downward", "weather disrupted crop yields"]}', :'s3_id', 2),
('passage_reconstruction', '{"passage": "The company faced backlash after customers discovered that the product''s advertised features were only partially functional."}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["company faced backlash", "advertised features were only partially functional"]}', :'s3_id', 3),
('passage_reconstruction', '{"passage": "The board approved the acquisition only after securing assurances that no jobs would be lost in the transition."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["board approved the acquisition", "secured assurances no jobs would be lost"]}', :'s3_id', 4),
('passage_reconstruction', '{"passage": "The study concluded that remote employees reported higher satisfaction, but also felt more disconnected from their teams."}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["remote employees had higher satisfaction", "felt more disconnected from teams"]}', :'s3_id', 5);

-- ===================== reading_comprehension =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('reading_comprehension', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('reading_comprehension', '{"passage": "Annual Report Summary: Revenue grew 8% while operating costs grew 12%, narrowing overall profit margins.", "question": "What happened to profit margins?", "options": ["They widened", "They narrowed", "They stayed the same", "They doubled"]}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s1_id', 1),
('reading_comprehension', '{"passage": "Memo: All expense reports over $500 now require director approval before reimbursement.", "question": "What requires director approval?", "options": ["All expense reports", "Reports over $500", "Reports under $500", "No reports"]}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s1_id', 2),
('reading_comprehension', '{"passage": "Notice: The library will extend its hours during exam week, staying open until midnight instead of 9 PM.", "question": "What is changing during exam week?", "options": ["Nothing", "Closing time moves later", "Closing time moves earlier", "The library closes entirely"]}', 0.57, 'B2', 'approved', 'manual', 'education', 'practice', '{"correctIndex": 1}', :'s1_id', 3),
('reading_comprehension', '{"passage": "Weather Advisory: A storm is expected Thursday evening, bringing strong winds but little rainfall.", "question": "What will the storm mainly bring?", "options": ["Heavy rain", "Strong winds", "Snow", "Nothing significant"]}', 0.56, 'B2', 'approved', 'manual', 'general', 'practice', '{"correctIndex": 1}', :'s1_id', 4),
('reading_comprehension', '{"passage": "Product Update: The new app version fixes login issues but temporarily disables offline mode.", "question": "What does the update disable?", "options": ["Login", "Offline mode", "Notifications", "Nothing"]}', 0.58, 'B2', 'approved', 'manual', 'technology', 'practice', '{"correctIndex": 1}', :'s1_id', 5),
('reading_comprehension', '{"passage": "Policy Update: Employees may now work from home up to three days per week, up from one day previously.", "question": "How many days could employees previously work from home?", "options": ["One", "Two", "Three", "Five"]}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s2_id', 1),
('reading_comprehension', '{"passage": "Market Update: Shares fell 4% after the company missed its quarterly earnings target.", "question": "Why did shares fall?", "options": ["Earnings exceeded targets", "Earnings missed targets", "A new product launched", "No reason given"]}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s2_id', 2),
('reading_comprehension', '{"passage": "Event Notice: The conference has been shortened from three days to two due to lower-than-expected registration.", "question": "Why was the conference shortened?", "options": ["Low registration", "Venue issues", "Weather", "Budget surplus"]}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s2_id', 3),
('reading_comprehension', '{"passage": "Safety Bulletin: Workers must now wear protective eyewear in all manufacturing zones, not just zone three.", "question": "Where was eyewear previously required?", "options": ["Everywhere", "Only zone three", "Nowhere", "Only the office"]}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s2_id', 4),
('reading_comprehension', '{"passage": "Travel Advisory: Due to construction, the highway exit will be closed on weekends only through next month.", "question": "When is the exit closed?", "options": ["Weekdays only", "Weekends only", "Every day", "Never"]}', 0.62, 'B2', 'approved', 'manual', 'travel', 'practice', '{"correctIndex": 1}', :'s2_id', 5),
('reading_comprehension', '{"passage": "Quarterly Review: Customer complaints decreased 30% after the new support system launched, though response times stayed roughly the same.", "question": "What improved after the new system launched?", "options": ["Response times", "Complaint volume", "Pricing", "Staffing"]}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s3_id', 1),
('reading_comprehension', '{"passage": "Policy Notice: Returns are accepted within 30 days with a receipt, or within 14 days without one.", "question": "How long do returns take without a receipt?", "options": ["30 days", "14 days", "7 days", "No returns allowed"]}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s3_id', 2),
('reading_comprehension', '{"passage": "Research Summary: The study sampled 500 participants, but only 420 completed every stage of the survey.", "question": "How many participants completed every stage?", "options": ["500", "420", "80", "All of them"]}', 0.67, 'B2', 'approved', 'manual', 'education', 'practice', '{"correctIndex": 1}', :'s3_id', 3),
('reading_comprehension', '{"passage": "Finance Memo: Despite a strong first half, the second half of the year saw revenue decline due to seasonal factors.", "question": "When did revenue decline?", "options": ["First half", "Second half", "All year", "It never declined"]}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s3_id', 4),
('reading_comprehension', '{"passage": "HR Update: Remote onboarding now takes five days, down from the previous two-week process.", "question": "How long did onboarding take before the change?", "options": ["Five days", "Two weeks", "One month", "One day"]}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s3_id', 5);

-- ===================== response_selection =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('response_selection', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('response_selection', '{"text": "The client is unhappy with the delivery delay.", "options": ["Let''s offer a partial refund and apologize.", "I enjoy deliveries.", "The weather was nice yesterday."]}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s1_id', 1),
('response_selection', '{"text": "Our competitor just cut their prices.", "options": ["We should reassess our pricing strategy.", "I like competitive sports.", "The office closes at five."]}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s1_id', 2),
('response_selection', '{"text": "The audit found some discrepancies.", "options": ["We need to investigate them immediately.", "The cafeteria serves lunch at noon.", "She''s on leave this week."]}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s1_id', 3),
('response_selection', '{"text": "The new hire seems overwhelmed already.", "options": ["Maybe we should pair her with a mentor.", "The printer is out of ink.", "It rained this morning."]}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s1_id', 4),
('response_selection', '{"text": "The supplier raised their prices unexpectedly.", "options": ["We should look for alternative suppliers.", "I prefer tea in the morning.", "The meeting room is booked."]}', 0.58, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s1_id', 5),
('response_selection', '{"text": "Sales have been flat for two quarters.", "options": ["We might need a new marketing approach.", "The building has six floors.", "He enjoys hiking on weekends."]}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s2_id', 1),
('response_selection', '{"text": "The server migration caused some downtime.", "options": ["Let''s notify affected customers right away.", "I like the color blue.", "The train was on time today."]}', 0.61, 'B2', 'approved', 'manual', 'technology', 'practice', '{"correctIndex": 0}', :'s2_id', 2),
('response_selection', '{"text": "The regulator wants more documentation.", "options": ["Let''s gather everything they requested.", "The cafe closes at nine.", "She loves painting landscapes."]}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s2_id', 3),
('response_selection', '{"text": "The team missed the sprint deadline.", "options": ["We should review what caused the delay.", "The parking lot was full.", "He ordered a sandwich."]}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s2_id', 4),
('response_selection', '{"text": "The investor wants more financial detail before committing.", "options": ["Let''s prepare a more detailed report.", "The weather looks cloudy today.", "I enjoy jogging in the park."]}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s2_id', 5),
('response_selection', '{"text": "The merger negotiations have stalled completely.", "options": ["Perhaps we need a neutral mediator.", "The museum opens at ten.", "She bought new shoes yesterday."]}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s3_id', 1),
('response_selection', '{"text": "Our biggest client is threatening to leave.", "options": ["We should schedule an urgent meeting with them.", "The library is quiet today.", "He likes playing chess."]}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s3_id', 2),
('response_selection', '{"text": "The factory failed its latest safety inspection.", "options": ["We need to address the violations right away.", "The coffee shop is new.", "She traveled to Spain last year."]}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s3_id', 3),
('response_selection', '{"text": "Shareholders are questioning the recent spending.", "options": ["We should be transparent about our reasoning.", "The park has many trees.", "He forgot his umbrella."]}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s3_id', 4),
('response_selection', '{"text": "The product recall is costing us significantly.", "options": ["Let''s calculate the full financial impact.", "The bakery smells wonderful.", "She enjoys classical music."]}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s3_id', 5);

-- ===================== passage_comprehension =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('passage_comprehension', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('passage_comprehension', '{"story": "A regional manager noticed declining sales at one branch. After visiting in person, she found the staff were undertrained on the new product line.", "question": "What did the manager find?"}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["staff were undertrained", "undertrained staff"]}', :'s1_id', 1),
('passage_comprehension', '{"story": "A software team released an update too quickly, which introduced several new bugs. They rolled it back and tested more thoroughly before relaunching.", "question": "What did the team do after the bugs appeared?"}', 0.56, 'B2', 'approved', 'manual', 'technology', 'practice', '{"acceptable_answers": ["rolled it back and tested more", "rolled back the update"]}', :'s1_id', 2),
('passage_comprehension', '{"story": "A restaurant owner noticed fewer customers on weekday evenings. She introduced a discount for early diners, and weekday business picked up noticeably.", "question": "What did the owner introduce?"}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["a discount for early diners", "an early-dining discount"]}', :'s1_id', 3),
('passage_comprehension', '{"story": "A university noticed a drop in applications from international students. After surveying them, they simplified the visa guidance on their website.", "question": "What did the university do?"}', 0.56, 'B2', 'approved', 'manual', 'education', 'practice', '{"acceptable_answers": ["simplified the visa guidance", "simplified website guidance"]}', :'s1_id', 4),
('passage_comprehension', '{"story": "A delivery company kept missing time windows in one area. Investigating further, they found traffic patterns had changed after new road construction.", "question": "What caused the missed time windows?"}', 0.58, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["changed traffic patterns", "road construction"]}', :'s1_id', 5),
('passage_comprehension', '{"story": "A bank noticed a rise in fraudulent transactions online. They introduced two-factor authentication, and fraud cases dropped sharply within weeks.", "question": "What did the bank introduce?"}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["two-factor authentication", "2FA"]}', :'s2_id', 1),
('passage_comprehension', '{"story": "A publisher noticed e-book sales outpacing print for the first time. They shifted marketing budget toward digital channels going forward.", "question": "What did the publisher do?"}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["shifted budget toward digital channels", "focused more on digital marketing"]}', :'s2_id', 2),
('passage_comprehension', '{"story": "A clinic struggled with missed appointments. They started sending automated reminder texts, and no-show rates fell considerably.", "question": "What did the clinic start doing?"}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["sending reminder texts", "automated text reminders"]}', :'s2_id', 3),
('passage_comprehension', '{"story": "A city noticed rising complaints about potholes. They launched an app allowing residents to report locations directly, speeding up repairs.", "question": "What did the city launch?"}', 0.60, 'B2', 'approved', 'manual', 'community', 'practice', '{"acceptable_answers": ["an app for reporting potholes", "a reporting app"]}', :'s2_id', 4),
('passage_comprehension', '{"story": "A manufacturer faced rising return rates for one product. After investigation, they found the instructions were unclear and rewrote them.", "question": "What was the cause of the returns?"}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["unclear instructions", "confusing instructions"]}', :'s2_id', 5),
('passage_comprehension', '{"story": "An airline faced criticism over unclear baggage fees. In response, they redesigned their website to display all fees upfront before booking.", "question": "What did the airline redesign?"}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["their website", "the booking website"]}', :'s3_id', 1),
('passage_comprehension', '{"story": "A nonprofit saw donations decline during a recession. They shifted their messaging to emphasize smaller, recurring contributions instead of large one-time gifts.", "question": "What change did the nonprofit make?"}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["emphasized recurring donations", "promoted smaller recurring gifts"]}', :'s3_id', 2),
('passage_comprehension', '{"story": "A tech company''s customer support response times grew worse as the user base expanded. They hired and trained a dedicated overnight support team.", "question": "What did the company do to fix response times?"}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["hired an overnight support team", "added overnight support staff"]}', :'s3_id', 3),
('passage_comprehension', '{"story": "A school noticed test scores plateauing despite more funding. An independent review found outdated teaching methods were the main issue.", "question": "What did the review find?"}', 0.65, 'B2', 'approved', 'manual', 'education', 'practice', '{"acceptable_answers": ["outdated teaching methods", "the teaching methods were outdated"]}', :'s3_id', 4),
('passage_comprehension', '{"story": "A logistics firm faced driver shortages during peak season. They began offering seasonal bonuses, which helped attract temporary staff quickly.", "question": "What did the firm begin offering?"}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["seasonal bonuses", "bonuses for seasonal staff"]}', :'s3_id', 5);

-- ===================== story_retelling =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('story_retelling', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('story_retelling', '{"story": "After months of declining sales, a small bookstore owner decided to host weekly author events. Attendance grew steadily, and the events eventually brought in enough new customers to reverse the decline."}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('story_retelling', '{"story": "A young engineer proposed an unconventional fix for a recurring equipment failure. Senior staff were skeptical at first, but after testing, the fix worked and became standard practice."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('story_retelling', '{"story": "A city struggled with overcrowded buses during rush hour. Officials introduced a staggered work-hour policy for government employees, which noticeably eased congestion."}', 0.57, 'B2', 'approved', 'manual', 'community', 'practice', :'s1_id', 3),
('story_retelling', '{"story": "A restaurant chain faced criticism for inconsistent food quality across locations. They retrained all kitchen staff using a standardized recipe guide, and complaints dropped significantly."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('story_retelling', '{"story": "A university professor noticed students struggling with a difficult textbook. She created simplified supplementary notes, and test scores improved across the class."}', 0.58, 'B2', 'approved', 'manual', 'education', 'practice', :'s1_id', 5),
('story_retelling', '{"story": "A startup''s first product failed to gain traction. The founders pivoted to a different market segment based on user feedback, and the company eventually became profitable."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('story_retelling', '{"story": "A factory experienced frequent safety violations despite repeated warnings. Management introduced mandatory safety briefings before every shift, and violations decreased substantially."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('story_retelling', '{"story": "A hospital''s emergency room faced long patient wait times. Staff redesigned the intake process to triage patients more efficiently, cutting average wait times nearly in half."}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('story_retelling', '{"story": "A software company struggled with a high number of support tickets about the same issue. They created a detailed help article addressing it directly, and ticket volume dropped sharply."}', 0.60, 'B2', 'approved', 'manual', 'technology', 'practice', :'s2_id', 4),
('story_retelling', '{"story": "A charity noticed donor engagement declining over several years. They began sharing detailed impact reports showing exactly how funds were used, which renewed donor confidence."}', 0.62, 'B2', 'approved', 'manual', 'community', 'practice', :'s2_id', 5),
('story_retelling', '{"story": "A manufacturing firm discovered a competitor was undercutting its prices significantly. Rather than matching the price, they emphasized product quality and customer service in their marketing, retaining most loyal customers."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('story_retelling', '{"story": "An airline faced backlash after a widely publicized service failure. The CEO personally addressed the issue publicly and offered compensation, which helped restore some public trust."}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('story_retelling', '{"story": "A research team''s initial hypothesis was disproven by their own data. Rather than discarding the project, they pursued the unexpected finding, which led to a more significant discovery."}', 0.67, 'B2', 'approved', 'manual', 'education', 'practice', :'s3_id', 3),
('story_retelling', '{"story": "A retailer noticed that a popular product was frequently out of stock. They renegotiated terms with their supplier to secure priority shipments, resolving the shortage within a month."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('story_retelling', '{"story": "A city government faced pushback over a proposed tax increase. After hosting several public forums to explain the reasoning, opposition softened and the measure eventually passed."}', 0.68, 'B2', 'approved', 'manual', 'community', 'practice', :'s3_id', 5);

-- ===================== speaking_situations =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('speaking_situations', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('speaking_situations', '{"situation": "You need to tell a client that their project will cost more than originally quoted. What would you say?"}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('speaking_situations', '{"situation": "A colleague takes credit for an idea that was actually yours. What would you say to them?"}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('speaking_situations', '{"situation": "You need to decline a meeting invitation because it conflicts with another priority. What would you say?"}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('speaking_situations', '{"situation": "Your team missed a target, and your manager asks for an explanation. What would you say?"}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('speaking_situations', '{"situation": "You need to ask a vendor for a discount on a large order. What would you say?"}', 0.58, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('speaking_situations', '{"situation": "A customer is upset about a mistake in their order. What would you say to resolve it?"}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('speaking_situations', '{"situation": "You disagree with a decision your manager made in a meeting. What would you say to raise your concern?"}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('speaking_situations', '{"situation": "You need to ask for an extension on an important deadline. What would you say?"}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('speaking_situations', '{"situation": "A new employee keeps making the same mistake. What would you say to help them improve?"}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('speaking_situations', '{"situation": "You need to explain to investors why quarterly results fell short. What would you say?"}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('speaking_situations', '{"situation": "You must deliver news of layoffs to your team. What would you say?"}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('speaking_situations', '{"situation": "A long-term client is considering switching to a competitor. What would you say to retain them?"}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('speaking_situations', '{"situation": "You need to mediate a disagreement between two team members. What would you say?"}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('speaking_situations', '{"situation": "You must explain a policy change that employees will likely dislike. What would you say?"}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('speaking_situations', '{"situation": "You need to push back on an unreasonable request from a senior executive. What would you say?"}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== open_questions =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('open_questions', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('open_questions', '{"prompt": "What do you think is the biggest challenge facing small businesses today?"}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('open_questions', '{"prompt": "How important is it for companies to be environmentally responsible?"}', 0.56, 'B2', 'approved', 'manual', 'environment', 'practice', :'s1_id', 2),
('open_questions', '{"prompt": "What makes a job genuinely satisfying, in your opinion?"}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('open_questions', '{"prompt": "Do you think social media has had a positive or negative effect on society?"}', 0.56, 'B2', 'approved', 'manual', 'culture', 'practice', :'s1_id', 4),
('open_questions', '{"prompt": "What role should governments play in regulating new technology?"}', 0.58, 'B2', 'approved', 'manual', 'technology', 'practice', :'s1_id', 5),
('open_questions', '{"prompt": "How has remote work changed the way people think about their careers?"}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('open_questions', '{"prompt": "What are the benefits and drawbacks of living in a large city?"}', 0.61, 'B2', 'approved', 'manual', 'community', 'practice', :'s2_id', 2),
('open_questions', '{"prompt": "Do you believe higher education is still worth the cost today?"}', 0.60, 'B2', 'approved', 'manual', 'education', 'practice', :'s2_id', 3),
('open_questions', '{"prompt": "What qualities make someone an effective leader?"}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('open_questions', '{"prompt": "How should companies balance profit with social responsibility?"}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('open_questions', '{"prompt": "Is competition or cooperation more valuable in building a successful team?"}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('open_questions', '{"prompt": "What impact do you think automation will have on future employment?"}', 0.66, 'B2', 'approved', 'manual', 'technology', 'practice', :'s3_id', 2),
('open_questions', '{"prompt": "How should society address the growing gap between rich and poor?"}', 0.67, 'B2', 'approved', 'manual', 'general', 'practice', :'s3_id', 3),
('open_questions', '{"prompt": "Do you think traditional offices will still exist in twenty years?"}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('open_questions', '{"prompt": "What responsibility do companies have toward the communities they operate in?"}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== email_writing =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('email_writing', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('email_writing', '{"prompt": "Write an email to your manager explaining why a client deadline needs to be pushed back by one week."}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('email_writing', '{"prompt": "Write an email to a vendor requesting a discount on a large bulk order."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('email_writing', '{"prompt": "Write an email to a coworker proposing a new way to organize weekly team meetings."}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('email_writing', '{"prompt": "Write an email declining a meeting invitation and suggesting an alternative time."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('email_writing', '{"prompt": "Write an email to a client apologizing for a billing error and explaining the correction."}', 0.58, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('email_writing', '{"prompt": "Write an email to your team announcing a change in the project timeline."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('email_writing', '{"prompt": "Write an email requesting feedback on a proposal you recently submitted."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('email_writing', '{"prompt": "Write an email to HR asking about the process for requesting additional vacation days."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('email_writing', '{"prompt": "Write an email to a supplier addressing a recent delay in shipment."}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('email_writing', '{"prompt": "Write an email proposing a new employee recognition program to your manager."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('email_writing', '{"prompt": "Write an email to a client explaining why their requested feature cannot be delivered this quarter."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('email_writing', '{"prompt": "Write an email to senior management recommending a change in company policy."}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('email_writing', '{"prompt": "Write an email addressing a conflict between two departments over shared resources."}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('email_writing', '{"prompt": "Write an email to investors summarizing a difficult quarter and the plan going forward."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('email_writing', '{"prompt": "Write an email announcing a restructuring and reassuring staff about their roles."}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== summary_and_opinion =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('summary_and_opinion', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('summary_and_opinion', '{"passage": "More schools are introducing coding classes at an early age. Supporters say it builds valuable problem-solving skills, while critics argue it takes time away from other important subjects."}', 0.55, 'B2', 'approved', 'manual', 'education', 'practice', '{"key_points": ["schools introduce early coding classes", "supporters cite problem-solving skills", "critics worry about time away from other subjects"]}', :'s1_id', 1),
('summary_and_opinion', '{"passage": "Many cities are banning single-use plastic bags. Environmentalists praise the move, while some small business owners worry about the added cost of alternatives."}', 0.56, 'B2', 'approved', 'manual', 'environment', 'practice', '{"key_points": ["cities ban single-use plastic bags", "environmentalists praise it", "business owners worry about costs"]}', :'s1_id', 2),
('summary_and_opinion', '{"passage": "Companies are increasingly monitoring employee productivity through software. Supporters say it improves accountability, but critics argue it damages trust and morale."}', 0.57, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["companies monitor productivity with software", "supporters cite accountability", "critics say it damages trust"]}', :'s1_id', 3),
('summary_and_opinion', '{"passage": "Some airlines now charge extra for carry-on luggage. The airlines say it keeps base fares lower, but passengers often feel misled by the final total cost."}', 0.56, 'B2', 'approved', 'manual', 'travel', 'practice', '{"key_points": ["airlines charge extra for carry-on", "airlines say it lowers base fares", "passengers feel misled by final cost"]}', :'s1_id', 4),
('summary_and_opinion', '{"passage": "Universities are expanding online degree programs. Proponents highlight flexibility and lower costs, while skeptics question whether online learning matches in-person quality."}', 0.58, 'B2', 'approved', 'manual', 'education', 'practice', '{"key_points": ["universities expand online degrees", "proponents cite flexibility and cost", "skeptics question quality"]}', :'s1_id', 5),
('summary_and_opinion', '{"passage": "A growing number of retailers are removing self-checkout machines after rising theft. Some customers appreciate faster service with cashiers, while others preferred the convenience of self-checkout."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["retailers remove self-checkout machines", "theft was rising", "some miss the convenience"]}', :'s2_id', 1),
('summary_and_opinion', '{"passage": "Several governments are considering a four-day work week trial. Advocates cite improved wellbeing, while opponents worry about reduced output in certain industries."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["governments consider four-day work week trials", "advocates cite wellbeing", "opponents worry about output"]}', :'s2_id', 2),
('summary_and_opinion', '{"passage": "More restaurants are adding mandatory service charges instead of relying on tips. Supporters say it creates fairer pay, while some customers feel it removes their choice."}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["restaurants add mandatory service charges", "supporters cite fairer pay", "customers feel it removes choice"]}', :'s2_id', 3),
('summary_and_opinion', '{"passage": "Public libraries are increasingly offering digital services like e-books and streaming. Fans say it modernizes the library, while others feel it strays from the library''s traditional purpose."}', 0.60, 'B2', 'approved', 'manual', 'culture', 'practice', '{"key_points": ["libraries offer more digital services", "fans say it modernizes libraries", "others feel it strays from tradition"]}', :'s2_id', 4),
('summary_and_opinion', '{"passage": "Some companies are requiring employees to return to the office full-time. Supporters argue it strengthens collaboration, while employees often cite the loss of flexibility."}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["companies require full return to office", "supporters cite collaboration", "employees cite lost flexibility"]}', :'s2_id', 5),
('summary_and_opinion', '{"passage": "Several cities have introduced congestion pricing for vehicles entering downtown areas. Officials say it reduces traffic and funds public transit, while drivers often view it as an unfair extra cost."}', 0.65, 'B2', 'approved', 'manual', 'community', 'practice', '{"key_points": ["cities introduce congestion pricing", "officials cite reduced traffic and transit funding", "drivers see it as unfair"]}', :'s3_id', 1),
('summary_and_opinion', '{"passage": "A growing number of employers are using AI tools to screen job applications. Supporters say it saves time, while critics worry qualified candidates may be unfairly filtered out."}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["employers use AI to screen applications", "supporters cite time savings", "critics worry about unfair filtering"]}', :'s3_id', 2),
('summary_and_opinion', '{"passage": "Some national parks are now limiting daily visitor numbers. Conservationists support the limits to protect ecosystems, while tourism businesses worry about lost revenue."}', 0.67, 'B2', 'approved', 'manual', 'environment', 'practice', '{"key_points": ["parks limit daily visitors", "conservationists support protecting ecosystems", "tourism businesses worry about revenue"]}', :'s3_id', 3),
('summary_and_opinion', '{"passage": "Several banks are closing physical branches in favor of online banking. Supporters cite lower costs, while elderly and rural customers often struggle with the shift."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["banks close branches for online banking", "supporters cite lower costs", "elderly and rural customers struggle"]}', :'s3_id', 4),
('summary_and_opinion', '{"passage": "Many companies now require job candidates to complete timed skills tests before interviews. Supporters say it ensures fairness, while critics argue it adds unnecessary pressure and favors test-takers over practical experience."}', 0.68, 'B2', 'approved', 'manual', 'business', 'practice', '{"key_points": ["companies require timed skills tests", "supporters say it ensures fairness", "critics say it favors test-takers over experience"]}', :'s3_id', 5);

-- ===================== typing =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('typing', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('typing', '{"text": "Despite the challenges of managing a distributed team, many companies have found that clear communication tools make remote collaboration surprisingly effective."}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('typing', '{"text": "The committee reviewed dozens of proposals before narrowing the list down to three finalists for further consideration."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('typing', '{"text": "Although the initial rollout faced technical issues, the updated system now processes transactions far more reliably."}', 0.57, 'B2', 'approved', 'manual', 'technology', 'practice', :'s1_id', 3),
('typing', '{"text": "Customer feedback suggested that the checkout process was too complicated, prompting the team to simplify it significantly."}', 0.56, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('typing', '{"text": "The city''s new recycling program has reduced landfill waste considerably over the past twelve months."}', 0.58, 'B2', 'approved', 'manual', 'environment', 'practice', :'s1_id', 5),
('typing', '{"text": "The negotiation team spent several weeks drafting terms that both sides could agree on without further delays."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('typing', '{"text": "Analysts believe the recent price increase reflects rising production costs rather than reduced competition in the market."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('typing', '{"text": "The hospital introduced a new scheduling system that reduced patient wait times by nearly half."}', 0.60, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('typing', '{"text": "Employees were encouraged to share feedback anonymously, which led to several unexpected and useful suggestions."}', 0.62, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('typing', '{"text": "The startup struggled initially, but a well-timed partnership helped it gain traction in a crowded market."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('typing', '{"text": "While automation has eliminated some roles, it has also created new positions requiring different, often more specialized skills."}', 0.65, 'B2', 'approved', 'manual', 'technology', 'practice', :'s3_id', 1),
('typing', '{"text": "The board ultimately approved the merger after securing commitments to protect existing employee contracts."}', 0.66, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('typing', '{"text": "Critics argue the policy addresses symptoms rather than the underlying causes of the housing shortage."}', 0.67, 'B2', 'approved', 'manual', 'community', 'practice', :'s3_id', 3),
('typing', '{"text": "Despite years of planning, the construction project encountered unexpected regulatory obstacles that delayed completion."}', 0.65, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('typing', '{"text": "The researchers acknowledged that although the findings were promising, further long-term studies were still required."}', 0.68, 'B2', 'approved', 'manual', 'education', 'practice', :'s3_id', 5);

-- ===================== free_writing =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('free_writing', 'B2 - Upper Intermediate', 4) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('free_writing', '{"prompt": "Write a paragraph discussing whether companies should allow employees to choose their own working hours."}', 0.55, 'B2', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('free_writing', '{"prompt": "Write a paragraph about the advantages and disadvantages of online shopping compared to in-store shopping."}', 0.56, 'B2', 'approved', 'manual', 'shopping', 'practice', :'s1_id', 2),
('free_writing', '{"prompt": "Write a paragraph describing a time you had to solve a difficult problem at work or school."}', 0.57, 'B2', 'approved', 'manual', 'general', 'practice', :'s1_id', 3),
('free_writing', '{"prompt": "Write a paragraph discussing whether schools should teach financial literacy as a required subject."}', 0.56, 'B2', 'approved', 'manual', 'education', 'practice', :'s1_id', 4),
('free_writing', '{"prompt": "Write a paragraph about how technology has changed the way people make friends."}', 0.58, 'B2', 'approved', 'manual', 'technology', 'practice', :'s1_id', 5),
('free_writing', '{"prompt": "Write a paragraph discussing whether cities should restrict private cars to reduce pollution."}', 0.60, 'B2', 'approved', 'manual', 'environment', 'practice', :'s2_id', 1),
('free_writing', '{"prompt": "Write a paragraph about the pros and cons of working for a large company versus a small startup."}', 0.61, 'B2', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('free_writing', '{"prompt": "Write a paragraph describing how you deal with stress during busy periods."}', 0.60, 'B2', 'approved', 'manual', 'general', 'practice', :'s2_id', 3),
('free_writing', '{"prompt": "Write a paragraph discussing whether universities should offer more vocational, job-focused programs."}', 0.62, 'B2', 'approved', 'manual', 'education', 'practice', :'s2_id', 4),
('free_writing', '{"prompt": "Write a paragraph about whether advertising aimed at children should be restricted."}', 0.61, 'B2', 'approved', 'manual', 'culture', 'practice', :'s2_id', 5),
('free_writing', '{"prompt": "Write a paragraph discussing whether governments should regulate how much time people spend on social media."}', 0.65, 'B2', 'approved', 'manual', 'technology', 'practice', :'s3_id', 1),
('free_writing', '{"prompt": "Write a paragraph about whether companies have a responsibility to address climate change beyond legal requirements."}', 0.66, 'B2', 'approved', 'manual', 'environment', 'practice', :'s3_id', 2),
('free_writing', '{"prompt": "Write a paragraph discussing whether remote job interviews are as effective as in-person ones."}', 0.67, 'B2', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('free_writing', '{"prompt": "Write a paragraph about whether success is better measured by income or personal satisfaction."}', 0.65, 'B2', 'approved', 'manual', 'general', 'practice', :'s3_id', 4),
('free_writing', '{"prompt": "Write a paragraph discussing whether artificial intelligence will create more jobs than it eliminates."}', 0.68, 'B2', 'approved', 'manual', 'technology', 'practice', :'s3_id', 5);

COMMIT;
