-- C1 units/sets for all 19 item types: 3 sets per type, 5 questions per
-- set, 15 items per type (285 total). Continues the band progression:
-- C1 0.68-0.80.
BEGIN;

-- ===================== reading =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('reading', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('reading', '{"text": "The committee''s reluctance to commit to a timeline has left stakeholders increasingly skeptical of the initiative''s viability."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('reading', '{"text": "Critics contend that the regulation, however well-intentioned, inadvertently stifles the very innovation it seeks to encourage."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('reading', '{"text": "What began as a modest pilot program has since evolved into a cornerstone of the organization''s long-term strategy."}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('reading', '{"text": "The findings, though preliminary, challenge several assumptions that have long underpinned conventional wisdom in the field."}', 0.68, 'C1', 'approved', 'manual', 'education', 'practice', :'s1_id', 4),
('reading', '{"text": "Negotiations stalled indefinitely once it became apparent that neither side was prepared to make meaningful concessions."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('reading', '{"text": "The firm''s reputation, once unassailable, has been gradually eroded by a series of ill-judged public statements."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('reading', '{"text": "Although the proposal garnered considerable enthusiasm initially, enthusiasm alone proved insufficient to secure its funding."}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('reading', '{"text": "The policy''s unintended consequences have prompted a reassessment of its underlying assumptions by its original architects."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('reading', '{"text": "Few anticipated that the merger, once finalized, would precipitate such a profound shift in market dynamics."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('reading', '{"text": "The study''s methodology has drawn scrutiny from peers who question whether its sample adequately represents the population."}', 0.74, 'C1', 'approved', 'manual', 'education', 'practice', :'s2_id', 5),
('reading', '{"text": "The board''s decision to proceed despite mounting objections has been characterized by some as reckless and by others as decisive."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('reading', '{"text": "Investors remain divided over whether the company''s aggressive expansion reflects genuine confidence or an attempt to mask underlying weaknesses."}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('reading', '{"text": "The report''s conclusions, while compelling, rest on assumptions that subsequent analysts have been reluctant to accept uncritically."}', 0.78, 'C1', 'approved', 'manual', 'education', 'practice', :'s3_id', 3),
('reading', '{"text": "What distinguishes this proposal from its predecessors is its willingness to confront, rather than circumvent, the underlying structural issues."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('reading', '{"text": "The dispute, having simmered for years, finally erupted into open conflict once the terms of the contract were disclosed publicly."}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== reading_selective =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('reading_selective', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('reading_selective', '{"text": "The clause stipulates that liability is capped at the contract value unless gross negligence can be demonstrated.", "question": "Under what condition does liability exceed the cap?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["gross negligence", "if gross negligence is shown"]}', :'s1_id', 1),
('reading_selective', '{"text": "The amendment was shelved indefinitely after lobbyists successfully argued it would disproportionately burden smaller firms.", "question": "Why was the amendment shelved?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["it would burden smaller firms", "disproportionate burden on small firms"]}', :'s1_id', 2),
('reading_selective', '{"text": "The audit revealed that discrepancies, though minor individually, collectively amounted to a significant shortfall.", "question": "What did the discrepancies amount to collectively?"}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["a significant shortfall", "a large shortfall"]}', :'s1_id', 3),
('reading_selective', '{"text": "The embargo will remain in effect until both parties ratify the revised terms of engagement.", "question": "What must happen for the embargo to end?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["both parties must ratify the terms", "ratification by both parties"]}', :'s1_id', 4),
('reading_selective', '{"text": "The panel''s ruling, though not legally binding, is expected to carry significant weight in future proceedings.", "question": "Is the ruling legally binding?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["no", "not legally binding"]}', :'s1_id', 5),
('reading_selective', '{"text": "The restructuring plan was abandoned once it became clear that projected savings had been substantially overstated.", "question": "Why was the restructuring plan abandoned?"}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["savings were overstated", "the projected savings were inflated"]}', :'s2_id', 1),
('reading_selective', '{"text": "The firm''s valuation hinges largely on assumptions about future growth that many analysts consider overly optimistic.", "question": "What do analysts consider overly optimistic?"}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["growth assumptions", "the growth projections"]}', :'s2_id', 2),
('reading_selective', '{"text": "The arbitration process was expedited after both parties agreed to waive their right to a formal hearing.", "question": "What did both parties waive?"}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["their right to a formal hearing", "a formal hearing"]}', :'s2_id', 3),
('reading_selective', '{"text": "The policy''s critics argue that its exemptions effectively undermine its stated purpose.", "question": "What do critics argue the exemptions do?"}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["undermine the policy''s purpose", "weaken its purpose"]}', :'s2_id', 4),
('reading_selective', '{"text": "The committee deferred judgment pending further evidence, despite pressure to issue an immediate ruling.", "question": "What did the committee do despite pressure?"}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["deferred judgment", "delayed its ruling"]}', :'s2_id', 5),
('reading_selective', '{"text": "The clause''s ambiguity has given rise to conflicting interpretations among legal scholars.", "question": "What has the clause''s ambiguity given rise to?"}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["conflicting interpretations", "disagreement among scholars"]}', :'s3_id', 1),
('reading_selective', '{"text": "The board''s tacit approval of the plan was interpreted by staff as an implicit endorsement of further cuts.", "question": "How did staff interpret the board''s tacit approval?"}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["as endorsement of further cuts", "an implicit endorsement"]}', :'s3_id', 2),
('reading_selective', '{"text": "The settlement precludes either party from disclosing its terms to third parties.", "question": "What does the settlement preclude?"}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["disclosing its terms", "revealing the terms"]}', :'s3_id', 3),
('reading_selective', '{"text": "The resolution was adopted unanimously, notwithstanding reservations expressed by several delegates beforehand.", "question": "Did any delegates express reservations?"}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["yes", "several did"]}', :'s3_id', 4),
('reading_selective', '{"text": "The firm''s insistence on confidentiality clauses has drawn criticism from former employees alleging a culture of silence.", "question": "What have former employees alleged?"}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["a culture of silence", "a culture of secrecy"]}', :'s3_id', 5);

-- ===================== repeats =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('repeats', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('repeats', '{"text": "The committee''s reluctance to commit left stakeholders increasingly skeptical of the initiative."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('repeats', '{"text": "Critics contend that the regulation inadvertently stifles the innovation it seeks to encourage."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('repeats', '{"text": "What began as a modest pilot has evolved into a cornerstone of the strategy."}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('repeats', '{"text": "The findings challenge assumptions that have long underpinned conventional wisdom."}', 0.68, 'C1', 'approved', 'manual', 'education', 'practice', :'s1_id', 4),
('repeats', '{"text": "Negotiations stalled once neither side was prepared to make meaningful concessions."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('repeats', '{"text": "The firm''s reputation has been gradually eroded by ill-judged public statements."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('repeats', '{"text": "The proposal garnered enthusiasm, but that proved insufficient to secure funding."}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('repeats', '{"text": "The policy''s unintended consequences prompted a reassessment of its assumptions."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('repeats', '{"text": "Few anticipated the merger would precipitate such a profound shift."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('repeats', '{"text": "The study''s methodology has drawn scrutiny over its sample size."}', 0.74, 'C1', 'approved', 'manual', 'education', 'practice', :'s2_id', 5),
('repeats', '{"text": "The board''s decision to proceed despite objections was seen as reckless by some."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('repeats', '{"text": "Investors remain divided over whether the expansion reflects genuine confidence."}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('repeats', '{"text": "The report''s conclusions rest on assumptions analysts are reluctant to accept."}', 0.78, 'C1', 'approved', 'manual', 'education', 'practice', :'s3_id', 3),
('repeats', '{"text": "This proposal confronts, rather than circumvents, the underlying structural issues."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('repeats', '{"text": "The dispute finally erupted once the contract terms were disclosed publicly."}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== short_answer =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('short_answer', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('short_answer', '{"question": "Why might shareholders challenge a board''s decision even when it is legally sound?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('short_answer', '{"question": "What distinguishes a genuine conflict of interest from a mere perception of one?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('short_answer', '{"question": "Why do regulators sometimes favor incremental reform over sweeping legislative change?"}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('short_answer', '{"question": "What risks does a company face by prioritizing short-term gains over long-term sustainability?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('short_answer', '{"question": "Why can excessive transparency sometimes undermine organizational trust rather than build it?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('short_answer', '{"question": "What explains the persistence of groupthink even in highly experienced teams?"}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('short_answer', '{"question": "Why might a company deliberately understate its own projected growth?"}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('short_answer', '{"question": "What are the limitations of relying solely on quantitative data for strategic decisions?"}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('short_answer', '{"question": "Why do mergers between culturally incompatible organizations often underperform expectations?"}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('short_answer', '{"question": "What justifies the use of non-disclosure agreements in competitive industries?"}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('short_answer', '{"question": "Why might regulatory bodies be reluctant to intervene even amid clear market failures?"}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('short_answer', '{"question": "What are the ethical implications of using predictive algorithms in hiring decisions?"}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('short_answer', '{"question": "Why does organizational culture often prove more difficult to change than formal policy?"}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('short_answer', '{"question": "What distinguishes calculated risk-taking from reckless decision-making in leadership?"}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('short_answer', '{"question": "Why might an organization resist disclosing an internal failure even when transparency would ultimately serve its interests?"}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== sentence_builds =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('sentence_builds', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('sentence_builds', '{"groups": ["were it not for", "the last-minute intervention", "the deal", "would have collapsed"]}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Were it not for the last-minute intervention, the deal would have collapsed.", "alternates": []}', :'s1_id', 1),
('sentence_builds', '{"groups": ["so great was the demand", "that", "the company", "struggled to keep up"]}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "So great was the demand that the company struggled to keep up.", "alternates": []}', :'s1_id', 2),
('sentence_builds', '{"groups": ["rarely has a decision", "been so", "universally", "criticized"]}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Rarely has a decision been so universally criticized.", "alternates": []}', :'s1_id', 3),
('sentence_builds', '{"groups": ["not until the audit concluded", "did the extent", "of the losses", "become clear"]}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Not until the audit concluded did the extent of the losses become clear.", "alternates": []}', :'s1_id', 4),
('sentence_builds', '{"groups": ["the proposal", "having been", "thoroughly vetted", "was finally approved"]}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "The proposal, having been thoroughly vetted, was finally approved.", "alternates": []}', :'s1_id', 5),
('sentence_builds', '{"groups": ["seldom does an organization", "admit", "its mistakes", "so openly"]}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Seldom does an organization admit its mistakes so openly.", "alternates": []}', :'s2_id', 1),
('sentence_builds', '{"groups": ["had the warning signs", "been heeded", "the crisis", "might have been averted"]}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Had the warning signs been heeded, the crisis might have been averted.", "alternates": []}', :'s2_id', 2),
('sentence_builds', '{"groups": ["only after considerable pressure", "did the executives", "agree to", "the independent review"]}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Only after considerable pressure did the executives agree to the independent review.", "alternates": []}', :'s2_id', 3),
('sentence_builds', '{"groups": ["so controversial was the ruling", "that", "it", "sparked nationwide debate"]}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "So controversial was the ruling that it sparked nationwide debate.", "alternates": []}', :'s2_id', 4),
('sentence_builds', '{"groups": ["little did the board anticipate", "how quickly", "the market", "would turn against them"]}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Little did the board anticipate how quickly the market would turn against them.", "alternates": []}', :'s2_id', 5),
('sentence_builds', '{"groups": ["not only was the merger approved", "but it", "was also", "praised by analysts"]}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Not only was the merger approved, but it was also praised by analysts.", "alternates": []}', :'s3_id', 1),
('sentence_builds', '{"groups": ["so deeply entrenched was the practice", "that", "reform", "proved nearly impossible"]}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "So deeply entrenched was the practice that reform proved nearly impossible.", "alternates": []}', :'s3_id', 2),
('sentence_builds', '{"groups": ["were the regulations", "enforced more strictly", "violations", "would be far less common"]}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Were the regulations enforced more strictly, violations would be far less common.", "alternates": []}', :'s3_id', 3),
('sentence_builds', '{"groups": ["rarely do negotiations", "proceed as", "smoothly as", "this one did"]}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Rarely do negotiations proceed as smoothly as this one did.", "alternates": []}', :'s3_id', 4),
('sentence_builds', '{"groups": ["not since the recession", "has the industry", "faced such", "widespread uncertainty"]}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', '{"correct": "Not since the recession has the industry faced such widespread uncertainty.", "alternates": []}', :'s3_id', 5);

-- ===================== conversations =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('conversations', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('conversations', '{"dialogue": "A: The regulator is threatening sanctions. B: On what grounds? A: Alleged non-compliance with disclosure requirements.", "question": "What is the alleged basis for sanctions?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["non-compliance with disclosure requirements", "disclosure violations"]}', :'s1_id', 1),
('conversations', '{"dialogue": "A: The board overruled the CEO. B: On the acquisition? A: Yes, citing excessive risk exposure.", "question": "Why did the board overrule the CEO?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["excessive risk exposure", "too much risk"]}', :'s1_id', 2),
('conversations', '{"dialogue": "A: The settlement terms leaked. B: How damaging is that? A: Potentially, given the confidentiality clause.", "question": "Why is the leak potentially damaging?"}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["there was a confidentiality clause", "breach of confidentiality"]}', :'s1_id', 3),
('conversations', '{"dialogue": "A: The audit flagged a conflict of interest. B: Involving whom? A: A senior director with undisclosed holdings.", "question": "Who was involved in the conflict of interest?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["a senior director", "the director with undisclosed holdings"]}', :'s1_id', 4),
('conversations', '{"dialogue": "A: The merger talks resumed. B: After the breakdown? A: Yes, under new leadership on both sides.", "question": "Under what circumstances did talks resume?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["under new leadership", "with new leadership on both sides"]}', :'s1_id', 5),
('conversations', '{"dialogue": "A: Shareholders are demanding accountability. B: For what specifically? A: The undisclosed losses from last quarter.", "question": "What are shareholders demanding accountability for?"}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["undisclosed losses", "the hidden losses"]}', :'s2_id', 1),
('conversations', '{"dialogue": "A: The whistleblower came forward. B: What did they allege? A: Systematic falsification of safety records.", "question": "What did the whistleblower allege?"}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["falsification of safety records", "falsified safety records"]}', :'s2_id', 2),
('conversations', '{"dialogue": "A: The tribunal issued its verdict. B: In whose favor? A: The plaintiff, though damages were reduced.", "question": "In whose favor did the tribunal rule?"}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["the plaintiff"]}', :'s2_id', 3),
('conversations', '{"dialogue": "A: The firm is restructuring its debt. B: Voluntarily? A: Not entirely, under pressure from creditors.", "question": "Is the restructuring entirely voluntary?"}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["no", "not entirely"]}', :'s2_id', 4),
('conversations', '{"dialogue": "A: The CEO resigned abruptly. B: Any explanation given? A: Only vague references to personal reasons.", "question": "What explanation was given for the resignation?"}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["personal reasons", "vague personal reasons"]}', :'s2_id', 5),
('conversations', '{"dialogue": "A: The commission''s findings were damning. B: Will there be consequences? A: Likely, though enforcement remains uncertain.", "question": "Is enforcement of consequences certain?"}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["no", "uncertain"]}', :'s3_id', 1),
('conversations', '{"dialogue": "A: The acquisition was blocked. B: By regulators? A: Yes, over monopoly concerns.", "question": "Why was the acquisition blocked?"}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["monopoly concerns", "antitrust concerns"]}', :'s3_id', 2),
('conversations', '{"dialogue": "A: The company''s defense rested on a technicality. B: Which one? A: A procedural flaw in how evidence was gathered.", "question": "What was the technicality?"}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["a procedural flaw", "how evidence was gathered"]}', :'s3_id', 3),
('conversations', '{"dialogue": "A: The investigation was quietly dropped. B: Why? A: Insufficient evidence, according to the official statement.", "question": "Why was the investigation dropped?"}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["insufficient evidence", "lack of evidence"]}', :'s3_id', 4),
('conversations', '{"dialogue": "A: The settlement was far larger than expected. B: Any public reaction? A: Mostly outrage over the lack of accountability.", "question": "What was the public reaction?"}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["outrage", "outrage over lack of accountability"]}', :'s3_id', 5);

-- ===================== sentence_completion =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('sentence_completion', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('sentence_completion', '{"sentence": "___ the evidence being circumstantial, the jury still returned a guilty verdict.", "hint_word": ""}', 0.68, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["despite", "notwithstanding"]}', :'s1_id', 1),
('sentence_completion', '{"sentence": "Had the firm acted sooner, the scandal ___ have been contained.", "hint_word": "could"}', 0.69, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["could"]}', :'s1_id', 2),
('sentence_completion', '{"sentence": "The policy, ___ well-intentioned, has produced several unintended consequences.", "hint_word": ""}', 0.70, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["while", "although"]}', :'s1_id', 3),
('sentence_completion', '{"sentence": "Rarely ___ a proposal received such unanimous support.", "hint_word": "have"}', 0.68, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["has"]}', :'s1_id', 4),
('sentence_completion', '{"sentence": "The settlement is contingent ___ both parties signing within thirty days.", "hint_word": ""}', 0.69, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["on", "upon"]}', :'s1_id', 5),
('sentence_completion', '{"sentence": "So great was the backlash ___ the policy was reversed within a week.", "hint_word": ""}', 0.72, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["that"]}', :'s2_id', 1),
('sentence_completion', '{"sentence": "The directive, once ratified, ___ binding on all subsidiaries.", "hint_word": "be"}', 0.73, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["will be", "becomes"]}', :'s2_id', 2),
('sentence_completion', '{"sentence": "Not until the report was published ___ the full extent of the damage understood.", "hint_word": "be"}', 0.74, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["was"]}', :'s2_id', 3),
('sentence_completion', '{"sentence": "The proposal was rejected on the grounds ___ it lacked sufficient funding.", "hint_word": ""}', 0.72, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["that"]}', :'s2_id', 4),
('sentence_completion', '{"sentence": "Were the merger to proceed, both companies ___ face significant regulatory scrutiny.", "hint_word": "face"}', 0.74, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["would face"]}', :'s2_id', 5),
('sentence_completion', '{"sentence": "Seldom ___ an organization admit fault so publicly.", "hint_word": "do"}', 0.76, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["does"]}', :'s3_id', 1),
('sentence_completion', '{"sentence": "The firm''s silence was interpreted ___ an implicit admission of guilt.", "hint_word": ""}', 0.77, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["as"]}', :'s3_id', 2),
('sentence_completion', '{"sentence": "Had the warning been heeded, the outcome ___ have been markedly different.", "hint_word": "might"}', 0.78, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["might"]}', :'s3_id', 3),
('sentence_completion', '{"sentence": "The ruling sets a precedent ___ future cases of a similar nature.", "hint_word": ""}', 0.76, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["for"]}', :'s3_id', 4),
('sentence_completion', '{"sentence": "So entrenched was the practice ___ reform proved almost impossible.", "hint_word": ""}', 0.79, 'C1', 'approved', 'manual', 'grammar', 'practice', '{"acceptable_answers": ["that"]}', :'s3_id', 5);

-- ===================== dictation =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('dictation', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('dictation', '{"text": "The regulator imposed sanctions despite the firm''s repeated assurances."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('dictation', '{"text": "The board overruled the CEO, citing excessive risk exposure."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('dictation', '{"text": "The settlement terms leaked despite a strict confidentiality clause."}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('dictation', '{"text": "The audit flagged an undisclosed conflict of interest involving a director."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('dictation', '{"text": "Merger talks resumed only after leadership changed on both sides."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('dictation', '{"text": "Shareholders demanded accountability for the undisclosed quarterly losses."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('dictation', '{"text": "The whistleblower alleged systematic falsification of safety records."}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('dictation', '{"text": "The tribunal ruled in the plaintiff''s favor, though damages were reduced."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('dictation', '{"text": "The firm is restructuring its debt under pressure from creditors."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('dictation', '{"text": "The CEO resigned abruptly, citing only vague personal reasons."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('dictation', '{"text": "The commission''s findings were damning, though enforcement remains uncertain."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('dictation', '{"text": "Regulators blocked the acquisition over concerns about monopoly power."}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('dictation', '{"text": "The company''s defense rested on a procedural flaw in the evidence."}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('dictation', '{"text": "The investigation was quietly dropped, citing insufficient evidence."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('dictation', '{"text": "Public outrage followed once the settlement amount was disclosed."}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== passage_reconstruction =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('passage_reconstruction', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('passage_reconstruction', '{"passage": "Regulators fined the bank after an investigation revealed that risk disclosures had been systematically understated for years, misleading both investors and oversight bodies."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["regulators fined the bank", "risk disclosures were understated for years", "investors and oversight bodies were misled"]}', :'s1_id', 1),
('passage_reconstruction', '{"passage": "The merger, once hailed as transformative, has since been quietly unwound after integration costs far exceeded initial projections, eroding much of the anticipated value."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the merger was hailed as transformative", "it was quietly unwound", "integration costs exceeded projections"]}', :'s1_id', 2),
('passage_reconstruction', '{"passage": "A whistleblower''s testimony prompted a formal inquiry into the agency''s procurement practices, revealing a pattern of favoritism toward a handful of politically connected contractors."}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["a whistleblower prompted an inquiry", "the inquiry looked at procurement practices", "it revealed favoritism toward connected contractors"]}', :'s1_id', 3),
('passage_reconstruction', '{"passage": "Despite assurances of transparency, the company''s decision to withhold the full audit from shareholders drew sharp criticism and renewed calls for governance reform."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the company withheld the full audit", "this drew sharp criticism", "it renewed calls for governance reform"]}', :'s1_id', 4),
('passage_reconstruction', '{"passage": "The court''s ruling, while narrow in scope, has been widely interpreted as a rebuke of the agency''s broader enforcement strategy."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the ruling was narrow in scope", "it was interpreted as a rebuke", "it concerned the agency''s enforcement strategy"]}', :'s1_id', 5),
('passage_reconstruction', '{"passage": "After years of resisting reform, the industry finally conceded to stricter oversight once a string of high-profile failures made the status quo untenable."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the industry resisted reform for years", "it conceded to stricter oversight", "high-profile failures made the status quo untenable"]}', :'s2_id', 1),
('passage_reconstruction', '{"passage": "The think tank''s report, though methodologically sound, was dismissed by critics who questioned the motives of its primary funders."}', 0.73, 'C1', 'approved', 'manual', 'education', 'practice', '{"key_points": ["the report was methodologically sound", "it was dismissed by critics", "critics questioned the funders'' motives"]}', :'s2_id', 2),
('passage_reconstruction', '{"passage": "The company''s stock plunged after an analyst revealed that reported revenues had been inflated through a series of undisclosed related-party transactions."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["stock plunged after an analyst''s report", "revenues were inflated", "this was done through undisclosed related-party transactions"]}', :'s2_id', 3),
('passage_reconstruction', '{"passage": "Although the settlement avoided a lengthy trial, critics argued it allowed the company to escape meaningful accountability for its conduct."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the settlement avoided a lengthy trial", "critics said it let the company escape accountability"]}', :'s2_id', 4),
('passage_reconstruction', '{"passage": "The agency''s sudden reversal on the policy, after years of defending it publicly, left many observers questioning what internal pressures had prompted the change."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the agency reversed its policy suddenly", "it had defended the policy for years", "observers questioned what pressures caused the change"]}', :'s2_id', 5),
('passage_reconstruction', '{"passage": "The inquiry concluded that systemic failures, rather than any single individual''s negligence, were ultimately responsible for the disaster."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the inquiry blamed systemic failures", "not any single individual''s negligence", "these failures caused the disaster"]}', :'s3_id', 1),
('passage_reconstruction', '{"passage": "The firm''s attempt to rebrand following the scandal was widely seen as superficial, failing to address the structural issues that had precipitated the crisis."}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the firm tried to rebrand after the scandal", "this was seen as superficial", "it failed to address the structural issues"]}', :'s3_id', 2),
('passage_reconstruction', '{"passage": "The legislation, drafted hastily in response to public outcry, has since been criticized for creating loopholes nearly as problematic as the practices it sought to eliminate."}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the legislation was drafted hastily", "it responded to public outcry", "it created new loopholes nearly as problematic"]}', :'s3_id', 3),
('passage_reconstruction', '{"passage": "The acquisition, pursued aggressively despite internal warnings, ultimately proved to be the catalyst for the company''s most severe financial crisis in a decade."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the acquisition was pursued despite warnings", "it became the catalyst for a financial crisis", "it was the worst crisis in a decade"]}', :'s3_id', 4),
('passage_reconstruction', '{"passage": "The commission''s recommendations, though well-received in principle, have languished for want of political will to implement them."}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["the recommendations were well-received in principle", "they have languished", "there is a lack of political will to implement them"]}', :'s3_id', 5);

-- ===================== reading_comprehension =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('reading_comprehension', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('reading_comprehension', '{"passage": "Legal Brief: The appellant argues the lower court erred by excluding key testimony, while the respondent maintains the exclusion was procedurally justified.", "question": "What does the appellant argue?", "options": ["The exclusion was justified", "The lower court erred", "No testimony was excluded", "The respondent is correct"]}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s1_id', 1),
('reading_comprehension', '{"passage": "Analyst Note: While headline revenue grew, margin compression driven by input costs raises concerns about underlying profitability.", "question": "What raises concerns about profitability?", "options": ["Revenue growth", "Margin compression", "Input cost reduction", "Nothing"]}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s1_id', 2),
('reading_comprehension', '{"passage": "Policy Brief: Proponents argue the measure will reduce emissions; opponents counter that enforcement mechanisms remain inadequately defined.", "question": "What do opponents counter?", "options": ["Emissions will not be reduced", "Enforcement is poorly defined", "The measure is too strict", "There is no opposition"]}', 0.70, 'C1', 'approved', 'manual', 'environment', 'practice', '{"correctIndex": 1}', :'s1_id', 3),
('reading_comprehension', '{"passage": "Internal Memo: Despite assurances to the contrary, the restructuring will result in the elimination of roughly 200 positions across three departments.", "question": "How many positions will be eliminated?", "options": ["None", "Roughly 200", "Three", "All positions"]}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s1_id', 4),
('reading_comprehension', '{"passage": "Research Abstract: The study''s conclusions, while statistically significant, may not generalize beyond the narrow demographic sampled.", "question": "What limits the conclusions'' generalizability?", "options": ["Lack of statistical significance", "The narrow demographic sampled", "Too large a sample", "Nothing limits it"]}', 0.69, 'C1', 'approved', 'manual', 'education', 'practice', '{"correctIndex": 1}', :'s1_id', 5),
('reading_comprehension', '{"passage": "Board Minutes: The motion to approve the acquisition passed by a narrow margin, with three directors abstaining over unresolved due-diligence concerns.", "question": "Why did three directors abstain?", "options": ["They opposed the acquisition", "Unresolved due-diligence concerns", "They were absent", "No reason given"]}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s2_id', 1),
('reading_comprehension', '{"passage": "Court Filing: The defense contends the contract''s ambiguous language should be interpreted in the defendant''s favor under established precedent.", "question": "What does the defense contend?", "options": ["The contract is unambiguous", "Ambiguity should favor the defendant", "There is no precedent", "The plaintiff should win"]}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s2_id', 2),
('reading_comprehension', '{"passage": "Financial Disclosure: Although the company reported a net loss, adjusted figures exclude a one-time charge related to the divested subsidiary.", "question": "What do adjusted figures exclude?", "options": ["Normal operating costs", "A one-time charge", "All revenue", "Nothing"]}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s2_id', 3),
('reading_comprehension', '{"passage": "Committee Report: While the pilot program showed promise, scaling it nationally would require funding levels the current budget cannot accommodate.", "question": "What would scaling the program require?", "options": ["Less funding", "Funding beyond the current budget", "No additional funding", "A smaller pilot"]}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s2_id', 4),
('reading_comprehension', '{"passage": "Arbitration Summary: The tribunal found in favor of the claimant on liability but reduced damages substantially due to contributory negligence.", "question": "Why were damages reduced?", "options": ["The claimant lost on liability", "Contributory negligence", "No damages were awarded", "The tribunal made an error"]}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s2_id', 5),
('reading_comprehension', '{"passage": "Regulatory Notice: The exemption applies only to firms with revenues below a specified threshold, a detail critics say disproportionately favors large incumbents.", "question": "What do critics say the exemption does?", "options": ["Favors small firms fairly", "Disproportionately favors large incumbents", "Applies to everyone equally", "Has no effect"]}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s3_id', 1),
('reading_comprehension', '{"passage": "Audit Summary: The discrepancies, though individually immaterial, collectively suggest a pattern of inadequate internal controls.", "question": "What do the discrepancies collectively suggest?", "options": ["Strong internal controls", "A pattern of inadequate controls", "No real issue", "Deliberate fraud only"]}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s3_id', 2),
('reading_comprehension', '{"passage": "Appellate Opinion: The majority held that the lower court''s interpretation was overly broad, while the dissent argued it was entirely consistent with precedent.", "question": "What did the majority hold?", "options": ["The interpretation was too narrow", "The interpretation was overly broad", "There was no interpretation issue", "The dissent was correct"]}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s3_id', 3),
('reading_comprehension', '{"passage": "Economic Outlook: Forecasters caution that while headline indicators appear positive, underlying structural weaknesses could undermine medium-term growth.", "question": "What could undermine medium-term growth?", "options": ["Positive headline indicators", "Underlying structural weaknesses", "Strong forecasting", "Nothing"]}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s3_id', 4),
('reading_comprehension', '{"passage": "Compliance Review: The review found that while no laws were technically broken, the firm''s practices fell well short of industry best practice.", "question": "What did the review conclude about the firm''s practices?", "options": ["They broke the law", "They fell short of best practice", "They exceeded best practice", "No conclusion was reached"]}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 1}', :'s3_id', 5);

-- ===================== response_selection =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('response_selection', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('response_selection', '{"text": "The regulator is threatening to impose sanctions.", "options": ["We need to review our compliance procedures immediately.", "The weather forecast looks favorable.", "He enjoys long weekends."]}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s1_id', 1),
('response_selection', '{"text": "A whistleblower has come forward with serious allegations.", "options": ["We must launch an independent investigation at once.", "The cafeteria menu changed today.", "She prefers working early mornings."]}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s1_id', 2),
('response_selection', '{"text": "Our largest shareholder is demanding board representation.", "options": ["We should schedule a formal discussion with them.", "The printer needs new toner.", "He takes the train to work."]}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s1_id', 3),
('response_selection', '{"text": "The auditors flagged a material weakness in our controls.", "options": ["We need to address this before the next filing.", "The office plants need watering.", "She''s learning to play guitar."]}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s1_id', 4),
('response_selection', '{"text": "A competitor has filed a patent infringement lawsuit against us.", "options": ["We should consult legal counsel right away.", "The coffee machine is being replaced.", "He likes hiking on weekends."]}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s2_id', 1),
('response_selection', '{"text": "The merger is facing antitrust scrutiny.", "options": ["We may need to divest certain assets to proceed.", "The parking garage is under renovation.", "She enjoys reading mystery novels."]}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s2_id', 2),
('response_selection', '{"text": "Our largest client is threatening to terminate the contract.", "options": ["Let''s arrange an urgent call to address their concerns.", "The building has a new elevator.", "He collects vintage stamps."]}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s2_id', 3),
('response_selection', '{"text": "The board is split over the proposed restructuring.", "options": ["We should present a more detailed cost-benefit analysis.", "The cafeteria closes at six.", "She''s planning a trip abroad."]}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s2_id', 4),
('response_selection', '{"text": "Regulators have requested additional documentation on our pricing model.", "options": ["We should compile everything they need promptly.", "He enjoys watching documentaries.", "The lobby was recently repainted."]}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s3_id', 1),
('response_selection', '{"text": "A key supplier has filed for bankruptcy protection.", "options": ["We need contingency plans for our supply chain.", "The vending machine is out of order.", "She prefers tea to coffee."]}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s3_id', 2),
('response_selection', '{"text": "The class-action lawsuit has gained significant media attention.", "options": ["We should coordinate closely with our communications team.", "The elevator is temporarily out of service.", "He enjoys cycling to work."]}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s3_id', 3),
('response_selection', '{"text": "An internal investigation uncovered falsified expense reports.", "options": ["We need to involve HR and legal immediately.", "The office recently got new furniture.", "She likes gardening on weekends."]}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s3_id', 4),
('response_selection', '{"text": "Credit rating agencies have placed us on a negative outlook.", "options": ["We should prepare a response for investor relations.", "The kitchen was recently remodeled.", "He enjoys playing the piano."]}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', '{"correctIndex": 0}', :'s3_id', 5);

-- ===================== passage_comprehension =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('passage_comprehension', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('passage_comprehension', '{"story": "A pharmaceutical company faced a lawsuit after a drug''s side effects were allegedly understated in clinical trial reports. The company settled out of court to avoid prolonged litigation, without admitting wrongdoing.", "question": "Why did the company settle?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["to avoid prolonged litigation", "avoid a long court case"]}', :'s1_id', 1),
('passage_comprehension', '{"story": "A pharmaceutical company faced a lawsuit after a drug''s side effects were allegedly understated in clinical trial reports. The company settled out of court to avoid prolonged litigation, without admitting wrongdoing.", "question": "Did the company admit wrongdoing?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["no", "they did not admit it"]}', :'s1_id', 2),
('passage_comprehension', '{"story": "A pharmaceutical company faced a lawsuit after a drug''s side effects were allegedly understated in clinical trial reports. The company settled out of court to avoid prolonged litigation, without admitting wrongdoing.", "question": "What was allegedly understated?"}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["the drug''s side effects", "side effects in trial reports"]}', :'s1_id', 3),
('passage_comprehension', '{"story": "A regional bank quietly tightened its lending standards after internal models flagged rising default risk in the commercial property sector. Competitors were slower to react, leaving them more exposed when the downturn arrived.", "question": "What did the bank tighten?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["its lending standards", "lending standards"]}', :'s1_id', 4),
('passage_comprehension', '{"story": "A regional bank quietly tightened its lending standards after internal models flagged rising default risk in the commercial property sector. Competitors were slower to react, leaving them more exposed when the downturn arrived.", "question": "What happened to competitors who reacted slowly?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["they were more exposed", "more exposed to the downturn"]}', :'s1_id', 5),
('passage_comprehension', '{"story": "A city''s transit authority faced criticism after an independent review found that ridership projections used to justify a costly expansion had been significantly overstated, raising questions about the project''s original approval.", "question": "What did the review find?"}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["ridership projections were overstated", "projections were inflated"]}', :'s2_id', 1),
('passage_comprehension', '{"story": "A city''s transit authority faced criticism after an independent review found that ridership projections used to justify a costly expansion had been significantly overstated, raising questions about the project''s original approval.", "question": "What questions did this raise?"}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["about the project''s original approval", "whether it should have been approved"]}', :'s2_id', 2),
('passage_comprehension', '{"story": "A technology firm''s stock dropped sharply after a former employee alleged in a lawsuit that the company had misrepresented its user growth figures to investors ahead of its public offering.", "question": "What did the former employee allege?"}', 0.74, 'C1', 'approved', 'manual', 'technology', 'practice', '{"acceptable_answers": ["misrepresented user growth figures", "inflated growth numbers"]}', :'s2_id', 3),
('passage_comprehension', '{"story": "A technology firm''s stock dropped sharply after a former employee alleged in a lawsuit that the company had misrepresented its user growth figures to investors ahead of its public offering.", "question": "When did this alleged misrepresentation happen?"}', 0.72, 'C1', 'approved', 'manual', 'technology', 'practice', '{"acceptable_answers": ["ahead of its public offering", "before the IPO"]}', :'s2_id', 4),
('passage_comprehension', '{"story": "An energy company was fined after regulators determined that emissions data submitted over several years had been calculated using an outdated and overly favorable methodology.", "question": "Why was the energy company fined?"}', 0.74, 'C1', 'approved', 'manual', 'environment', 'practice', '{"acceptable_answers": ["emissions data used an outdated methodology", "they miscalculated emissions"]}', :'s2_id', 5),
('passage_comprehension', '{"story": "A multinational retailer faced a prolonged labor dispute after workers at several distribution centers alleged unsafe conditions, prompting a government inquiry that ultimately substantiated several of their claims.", "question": "What did workers allege?"}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["unsafe conditions", "unsafe working conditions"]}', :'s3_id', 1),
('passage_comprehension', '{"story": "A multinational retailer faced a prolonged labor dispute after workers at several distribution centers alleged unsafe conditions, prompting a government inquiry that ultimately substantiated several of their claims.", "question": "What did the inquiry do?"}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["substantiated several claims", "confirmed some of the claims"]}', :'s3_id', 2),
('passage_comprehension', '{"story": "A prominent think tank retracted a widely cited study after independent researchers discovered that key data points had been selectively omitted to support a predetermined conclusion.", "question": "Why was the study retracted?"}', 0.78, 'C1', 'approved', 'manual', 'education', 'practice', '{"acceptable_answers": ["data was selectively omitted", "key data points were left out"]}', :'s3_id', 3),
('passage_comprehension', '{"story": "A prominent think tank retracted a widely cited study after independent researchers discovered that key data points had been selectively omitted to support a predetermined conclusion.", "question": "What did the omitted data support?"}', 0.76, 'C1', 'approved', 'manual', 'education', 'practice', '{"acceptable_answers": ["a predetermined conclusion", "a conclusion decided in advance"]}', :'s3_id', 4),
('passage_comprehension', '{"story": "An airline''s frequent cancellations during a holiday period led to a congressional hearing, where executives admitted that outdated scheduling software had been a significant contributing factor.", "question": "What did executives admit contributed to the cancellations?"}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', '{"acceptable_answers": ["outdated scheduling software", "old scheduling software"]}', :'s3_id', 5);

-- ===================== story_retelling =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('story_retelling', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('story_retelling', '{"story": "A mid-sized manufacturer discovered that a long-trusted supplier had been quietly substituting cheaper materials without disclosure. Rather than pursuing immediate legal action, the company renegotiated the contract with strict new quality clauses, preserving the relationship while protecting its interests."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('story_retelling', '{"story": "An established law firm lost several junior associates to a rival offering more flexible hours. Rather than matching the offer outright, the partners redesigned the firm''s entire career track to emphasize autonomy, which ultimately reduced turnover across the board."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('story_retelling', '{"story": "A city''s water utility faced mounting public anger after a contamination scare, even though testing later showed the risk had been minimal. Officials acknowledged that poor communication, more than the incident itself, had driven the backlash, and overhauled their crisis messaging accordingly."}', 0.70, 'C1', 'approved', 'manual', 'community', 'practice', :'s1_id', 3),
('story_retelling', '{"story": "A university''s endowment suffered losses after an overly aggressive investment strategy backfired during a market downturn. The board replaced its investment committee and adopted a far more conservative approach, prioritizing long-term stability over short-term returns."}', 0.68, 'C1', 'approved', 'manual', 'education', 'practice', :'s1_id', 4),
('story_retelling', '{"story": "A regional airline struggled for years with a reputation for poor customer service. A new CEO empowered frontline staff to resolve complaints on the spot without managerial approval, and customer satisfaction scores improved dramatically within a single year."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('story_retelling', '{"story": "A pharmaceutical firm faced intense pressure to rush a promising drug to market. Despite the financial incentive, the research team insisted on completing an additional trial phase, which ultimately uncovered a rare but serious side effect before the drug reached patients."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('story_retelling', '{"story": "A family-owned business resisted modernizing for decades, relying on loyal customers and tradition. When a younger generation took over, they introduced digital ordering cautiously, preserving the brand''s identity while finally reversing years of declining revenue."}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('story_retelling', '{"story": "A nonprofit organization discovered that a major donor''s funds had strings attached that conflicted with its mission. After considerable internal debate, the board declined the donation, a decision that initially strained finances but ultimately reinforced the organization''s credibility."}', 0.74, 'C1', 'approved', 'manual', 'community', 'practice', :'s2_id', 3),
('story_retelling', '{"story": "A manufacturing plant experienced a near-miss safety incident that could have been catastrophic. Rather than quietly addressing it internally, management disclosed the incident publicly and invited external auditors, a move that was initially unpopular but ultimately rebuilt worker trust."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('story_retelling', '{"story": "A software company''s flagship product was overtaken by a nimbler competitor within a single product cycle. Instead of competing directly, leadership chose to pivot toward an underserved enterprise niche, a decision that initially alarmed investors but eventually proved more profitable."}', 0.74, 'C1', 'approved', 'manual', 'technology', 'practice', :'s2_id', 5),
('story_retelling', '{"story": "A government agency''s decades-old procurement process had long been criticized as needlessly slow. A newly appointed director overhauled the system entirely, facing fierce resistance from entrenched staff, but ultimately cut average procurement times by more than half."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('story_retelling', '{"story": "A mining company faced sustained protests over its environmental record despite being in full legal compliance. Rather than dismissing the criticism, executives voluntarily adopted stricter standards than required, which gradually repaired the company''s public image over several years."}', 0.77, 'C1', 'approved', 'manual', 'environment', 'practice', :'s3_id', 2),
('story_retelling', '{"story": "A hospital system discovered that a significant proportion of readmissions stemmed from inadequate post-discharge instructions rather than clinical failures. Addressing this required no new technology, only a redesigned discharge process, yet it reduced readmissions more than any prior clinical intervention had."}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('story_retelling', '{"story": "A long-running family dispute over a company''s succession nearly led to its dissolution. An external mediator proposed splitting leadership roles along functional rather than hereditary lines, a compromise that satisfied no one entirely but preserved the business for another generation."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('story_retelling', '{"story": "A financial institution''s risk models had consistently underestimated the likelihood of a severe downturn, a flaw that only became apparent once the downturn actually occurred. The subsequent overhaul of its modeling assumptions became an industry case study in the limits of historical data."}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== speaking_situations =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('speaking_situations', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('speaking_situations', '{"situation": "You must inform a major investor that the company will miss its quarterly targets significantly. What would you say?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('speaking_situations', '{"situation": "A regulator has requested a meeting to discuss a potential compliance issue. What would you say to open the conversation?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('speaking_situations', '{"situation": "You need to tell a long-time business partner that the partnership is ending. What would you say?"}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('speaking_situations', '{"situation": "You must explain to the board why a major project failed despite careful planning. What would you say?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('speaking_situations', '{"situation": "A journalist asks you to comment on allegations of misconduct within your organization. What would you say?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('speaking_situations', '{"situation": "You need to persuade a skeptical client to accept a significant price increase. What would you say?"}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('speaking_situations', '{"situation": "You must deliver difficult feedback to a high-performing but disruptive team member. What would you say?"}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('speaking_situations', '{"situation": "You need to explain to employees why their pensions are being restructured. What would you say?"}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('speaking_situations', '{"situation": "A rival company has made an unsolicited acquisition offer, and your team is divided. What would you say to guide the discussion?"}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('speaking_situations', '{"situation": "You must inform a supplier that their contract will not be renewed after a long partnership. What would you say?"}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('speaking_situations', '{"situation": "You need to address employees after a data breach has exposed customer information. What would you say?"}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('speaking_situations', '{"situation": "You must convince a hesitant board to approve an unconventional but necessary strategy. What would you say?"}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('speaking_situations', '{"situation": "You need to respond to a public accusation that your company''s product caused harm. What would you say?"}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('speaking_situations', '{"situation": "You must explain to a founder why the company they built needs new leadership. What would you say?"}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('speaking_situations', '{"situation": "You need to negotiate with a union during a tense labor dispute. What would you say to open talks?"}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== open_questions =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('open_questions', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('open_questions', '{"prompt": "To what extent should companies be held accountable for the actions of their suppliers?"}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('open_questions', '{"prompt": "Is it ever justifiable for a company to prioritize shareholder interests over employee wellbeing?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('open_questions', '{"prompt": "How should societies balance innovation with the risks posed by unregulated emerging technologies?"}', 0.70, 'C1', 'approved', 'manual', 'technology', 'practice', :'s1_id', 3),
('open_questions', '{"prompt": "What obligations, if any, do successful individuals have toward the communities that helped shape them?"}', 0.68, 'C1', 'approved', 'manual', 'general', 'practice', :'s1_id', 4),
('open_questions', '{"prompt": "Can transparency alone restore trust in an institution that has lost public confidence?"}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('open_questions', '{"prompt": "Is economic growth an adequate measure of a society''s overall progress?"}', 0.72, 'C1', 'approved', 'manual', 'general', 'practice', :'s2_id', 1),
('open_questions', '{"prompt": "How should organizations weigh short-term financial pressure against long-term ethical considerations?"}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('open_questions', '{"prompt": "To what degree should individuals be responsible for verifying the information they share publicly?"}', 0.74, 'C1', 'approved', 'manual', 'culture', 'practice', :'s2_id', 3),
('open_questions', '{"prompt": "Does the pursuit of efficiency ever come at too great a cost to human judgment?"}', 0.72, 'C1', 'approved', 'manual', 'technology', 'practice', :'s2_id', 4),
('open_questions', '{"prompt": "What distinguishes legitimate dissent within an organization from disruptive insubordination?"}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('open_questions', '{"prompt": "Should historical injustices influence present-day corporate or governmental policy?"}', 0.76, 'C1', 'approved', 'manual', 'general', 'practice', :'s3_id', 1),
('open_questions', '{"prompt": "Is it possible to regulate artificial intelligence effectively without stifling its development?"}', 0.77, 'C1', 'approved', 'manual', 'technology', 'practice', :'s3_id', 2),
('open_questions', '{"prompt": "How should institutions respond when public opinion and expert consensus diverge sharply?"}', 0.78, 'C1', 'approved', 'manual', 'general', 'practice', :'s3_id', 3),
('open_questions', '{"prompt": "What role, if any, should sentiment play in decisions that are fundamentally economic in nature?"}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('open_questions', '{"prompt": "Can an organization genuinely reform its culture without a change in leadership?"}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== email_writing =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('email_writing', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('email_writing', '{"prompt": "Write an email to major investors explaining a significant and unexpected quarterly loss."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('email_writing', '{"prompt": "Write an email to a regulator responding to a formal inquiry into your company''s compliance practices."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('email_writing', '{"prompt": "Write an email to the board recommending the company proceed with a controversial but necessary layoff."}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('email_writing', '{"prompt": "Write an email to a long-term business partner formally ending the partnership."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('email_writing', '{"prompt": "Write an email to employees addressing concerns raised by a recent whistleblower complaint."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('email_writing', '{"prompt": "Write an email to a journalist responding to allegations of misconduct within your organization."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('email_writing', '{"prompt": "Write an email to shareholders explaining the rationale behind rejecting an acquisition offer."}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('email_writing', '{"prompt": "Write an email to a supplier terminating a long-standing contract due to repeated quality failures."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('email_writing', '{"prompt": "Write an email to employees explaining why pension benefits are being restructured."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('email_writing', '{"prompt": "Write an email to the board proposing an unconventional strategic pivot in response to market disruption."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('email_writing', '{"prompt": "Write an email to customers disclosing a data breach and explaining the steps being taken."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('email_writing', '{"prompt": "Write an email to a founder explaining the board''s decision to bring in new executive leadership."}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('email_writing', '{"prompt": "Write an email to union representatives proposing terms ahead of a tense labor negotiation."}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('email_writing', '{"prompt": "Write an email to investors defending the company against a short-seller''s public allegations."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('email_writing', '{"prompt": "Write an email to senior leadership recommending the company voluntarily disclose an internal failure before it becomes public."}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== summary_and_opinion =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('summary_and_opinion', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, answer_set, set_id, set_order) VALUES
('summary_and_opinion', '{"passage": "Several governments are debating whether to tax unrealized capital gains on large stock holdings. Proponents argue it would reduce wealth inequality, while opponents warn it could trigger capital flight and depress investment."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["governments debate taxing unrealized gains", "proponents cite reduced inequality", "opponents warn of capital flight"]}', :'s1_id', 1),
('summary_and_opinion', '{"passage": "A growing number of universities are reconsidering standardized testing requirements for admissions. Supporters of the change argue it broadens access, while critics worry it removes an objective benchmark for comparing applicants."}', 0.69, 'C1', 'approved', 'manual', 'education', 'practice', '{"key_points": ["universities reconsider testing requirements", "supporters cite broader access", "critics worry about losing an objective benchmark"]}', :'s1_id', 2),
('summary_and_opinion', '{"passage": "Some central banks are exploring digital currencies issued directly by the state. Advocates claim this would increase financial inclusion, while skeptics raise concerns about privacy and government overreach."}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["central banks explore digital currencies", "advocates cite financial inclusion", "skeptics raise privacy and overreach concerns"]}', :'s1_id', 3),
('summary_and_opinion', '{"passage": "A number of corporations are tying executive compensation to environmental and social metrics, not just financial performance. Supporters see this as overdue accountability, while critics call it a superficial gesture that obscures deeper issues."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["corporations tie pay to social/environmental metrics", "supporters see overdue accountability", "critics call it superficial"]}', :'s1_id', 4),
('summary_and_opinion', '{"passage": "Several nations are considering granting legal personhood to rivers and ecosystems to strengthen environmental protections. Proponents argue this creates stronger legal standing, while critics question how such rights could practically be enforced."}', 0.69, 'C1', 'approved', 'manual', 'environment', 'practice', '{"key_points": ["nations consider legal personhood for ecosystems", "proponents cite stronger legal standing", "critics question enforcement"]}', :'s1_id', 5),
('summary_and_opinion', '{"passage": "Some employers are experimenting with permanently eliminating performance reviews altogether, replacing them with continuous informal feedback. Supporters say this reduces anxiety and improves honesty, while skeptics worry it removes necessary structure and accountability."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["employers eliminate formal performance reviews", "supporters cite reduced anxiety", "skeptics worry about lost structure"]}', :'s2_id', 1),
('summary_and_opinion', '{"passage": "A debate has emerged over whether social media platforms should be legally liable for user-generated misinformation. Advocates of liability argue platforms profit from engagement regardless of harm, while opponents warn it would chill legitimate speech."}', 0.73, 'C1', 'approved', 'manual', 'technology', 'practice', '{"key_points": ["debate over platform liability for misinformation", "advocates cite profit from harmful engagement", "opponents warn of chilled speech"]}', :'s2_id', 2),
('summary_and_opinion', '{"passage": "Several countries are debating mandatory national service programs for young adults. Supporters argue it builds civic cohesion, while opponents view it as an infringement on individual liberty."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["debate over mandatory national service", "supporters cite civic cohesion", "opponents see it as infringing on liberty"]}', :'s2_id', 3),
('summary_and_opinion', '{"passage": "A growing number of companies are adopting four-day work weeks permanently rather than as a trial. Supporters cite sustained productivity gains, while skeptics argue early results may not hold across all industries long-term."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["companies adopt permanent four-day weeks", "supporters cite sustained productivity", "skeptics doubt long-term results across industries"]}', :'s2_id', 4),
('summary_and_opinion', '{"passage": "Some policymakers propose taxing automation to fund retraining for displaced workers. Proponents say this eases the transition fairly, while opponents argue it could slow beneficial technological adoption overall."}', 0.74, 'C1', 'approved', 'manual', 'technology', 'practice', '{"key_points": ["policymakers propose an automation tax", "proponents say it eases worker transitions", "opponents fear slowed technology adoption"]}', :'s2_id', 5),
('summary_and_opinion', '{"passage": "A controversial proposal would require corporations above a certain size to include worker representatives on their boards. Supporters argue this improves decision-making and accountability, while opponents contend it could slow governance and deter investment."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["proposal for worker board representation", "supporters cite better decisions and accountability", "opponents fear slower governance and less investment"]}', :'s3_id', 1),
('summary_and_opinion', '{"passage": "Some scientists argue that geoengineering, deliberately altering the climate to counteract warming, should be seriously researched as a last resort. Critics counter that it is far too risky and could discourage genuine emissions reduction."}', 0.77, 'C1', 'approved', 'manual', 'environment', 'practice', '{"key_points": ["scientists propose researching geoengineering", "it is framed as a last resort", "critics say it is risky and could discourage emissions cuts"]}', :'s3_id', 2),
('summary_and_opinion', '{"passage": "A debate has intensified over whether universities should divest entirely from fossil fuel companies in their endowments. Advocates argue it aligns investments with institutional values, while opponents claim it sacrifices financial returns needed for other priorities."}', 0.78, 'C1', 'approved', 'manual', 'education', 'practice', '{"key_points": ["debate over university fossil fuel divestment", "advocates cite aligning values with investment", "opponents cite sacrificed financial returns"]}', :'s3_id', 3),
('summary_and_opinion', '{"passage": "Some legal scholars argue that corporations found guilty of repeated serious violations should face the equivalent of a corporate death penalty, forced dissolution, rather than fines alone. Critics warn this would be disproportionate and harm innocent employees."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', '{"key_points": ["scholars propose forced dissolution for repeat offenders", "an alternative to fines alone", "critics warn it would harm innocent employees"]}', :'s3_id', 4),
('summary_and_opinion', '{"passage": "A growing debate concerns whether algorithmic pricing, where companies use AI to set prices dynamically based on individual data, constitutes unfair discrimination. Supporters call it efficient market pricing, while critics argue it exploits information asymmetries against consumers."}', 0.79, 'C1', 'approved', 'manual', 'technology', 'practice', '{"key_points": ["debate over algorithmic, individualized pricing", "supporters call it efficient pricing", "critics say it exploits information asymmetries"]}', :'s3_id', 5);

-- ===================== typing =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('typing', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('typing', '{"text": "The regulator''s decision to impose sanctions, though legally sound, has nonetheless provoked considerable debate over its broader economic implications."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('typing', '{"text": "Critics of the ruling argue that it sets a precedent likely to be exploited by future litigants in similarly ambiguous circumstances."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('typing', '{"text": "The board''s tacit approval of the restructuring plan was widely interpreted as an implicit endorsement of further cost reductions."}', 0.70, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 3),
('typing', '{"text": "Although the settlement avoided protracted litigation, many observers questioned whether it afforded meaningful accountability."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('typing', '{"text": "The firm''s reluctance to disclose the full extent of its losses has only intensified scrutiny from regulators and shareholders alike."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 5),
('typing', '{"text": "Analysts remain divided over whether the company''s aggressive expansion reflects genuine strategic confidence or an attempt to obscure underlying vulnerabilities."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('typing', '{"text": "The inquiry concluded that systemic shortcomings, rather than any single individual''s negligence, were ultimately responsible for the failure."}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('typing', '{"text": "Despite considerable internal resistance, the newly appointed director pressed ahead with reforms that many considered long overdue."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 3),
('typing', '{"text": "The committee''s findings, while methodologically rigorous, have nonetheless been contested by stakeholders with vested interests in the outcome."}', 0.72, 'C1', 'approved', 'manual', 'education', 'practice', :'s2_id', 4),
('typing', '{"text": "What distinguishes this proposal from its predecessors is its willingness to confront structural issues rather than merely circumvent them."}', 0.74, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 5),
('typing', '{"text": "The dispute, having simmered unresolved for years, finally erupted once the contested terms were disclosed to the public."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('typing', '{"text": "Shareholders have grown increasingly skeptical of management''s assurances, particularly given the pattern of understated risk disclosures."}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('typing', '{"text": "The policy''s critics contend that its exemptions effectively undermine the very objectives it was ostensibly designed to achieve."}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('typing', '{"text": "Few anticipated that the merger, once finalized, would precipitate such a profound and lasting shift in market dynamics."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 4),
('typing', '{"text": "The board''s decision to proceed despite mounting objections has since been characterized, depending on one''s perspective, as either decisive or reckless."}', 0.79, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 5);

-- ===================== free_writing =====================
INSERT INTO units (item_type_id, name, order_index) VALUES ('free_writing', 'C1 - Advanced', 5) RETURNING id \gset u_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 1', 1) RETURNING id \gset s1_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 2', 2) RETURNING id \gset s2_
INSERT INTO sets (unit_id, name, order_index) VALUES (:'u_id', 'Set 3', 3) RETURNING id \gset s3_
INSERT INTO items (item_type_id, content, difficulty, cefr_level, status, pipeline_version, topic, pool, set_id, set_order) VALUES
('free_writing', '{"prompt": "Write a paragraph arguing whether executive compensation should be legally capped relative to average employee pay."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 1),
('free_writing', '{"prompt": "Write a paragraph discussing whether whistleblowers deserve stronger legal protections than currently exist."}', 0.69, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 2),
('free_writing', '{"prompt": "Write a paragraph examining whether companies should be required to disclose the environmental impact of their entire supply chain."}', 0.70, 'C1', 'approved', 'manual', 'environment', 'practice', :'s1_id', 3),
('free_writing', '{"prompt": "Write a paragraph discussing whether governments should intervene when a company''s failure threatens broader economic stability."}', 0.68, 'C1', 'approved', 'manual', 'business', 'practice', :'s1_id', 4),
('free_writing', '{"prompt": "Write a paragraph arguing whether algorithmic decision-making should always allow for human override."}', 0.69, 'C1', 'approved', 'manual', 'technology', 'practice', :'s1_id', 5),
('free_writing', '{"prompt": "Write a paragraph discussing whether shareholder primacy should remain the dominant principle guiding corporate decisions."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 1),
('free_writing', '{"prompt": "Write a paragraph examining whether nondisclosure agreements should be restricted in cases involving workplace misconduct."}', 0.73, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 2),
('free_writing', '{"prompt": "Write a paragraph arguing whether universities bear responsibility for the career outcomes of their graduates."}', 0.74, 'C1', 'approved', 'manual', 'education', 'practice', :'s2_id', 3),
('free_writing', '{"prompt": "Write a paragraph discussing whether companies should be legally required to justify large-scale layoffs publicly."}', 0.72, 'C1', 'approved', 'manual', 'business', 'practice', :'s2_id', 4),
('free_writing', '{"prompt": "Write a paragraph examining whether international regulation of AI is realistic given competing national interests."}', 0.74, 'C1', 'approved', 'manual', 'technology', 'practice', :'s2_id', 5),
('free_writing', '{"prompt": "Write a paragraph arguing whether corporations convicted of repeated serious violations should face forced dissolution."}', 0.76, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 1),
('free_writing', '{"prompt": "Write a paragraph discussing whether central banks should issue government-backed digital currencies."}', 0.77, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 2),
('free_writing', '{"prompt": "Write a paragraph examining whether historical corporate wrongdoing should influence present-day regulatory treatment."}', 0.78, 'C1', 'approved', 'manual', 'business', 'practice', :'s3_id', 3),
('free_writing', '{"prompt": "Write a paragraph arguing whether automation taxes are a fair way to fund worker retraining programs."}', 0.76, 'C1', 'approved', 'manual', 'technology', 'practice', :'s3_id', 4),
('free_writing', '{"prompt": "Write a paragraph discussing whether legal personhood should be extended to natural ecosystems."}', 0.79, 'C1', 'approved', 'manual', 'environment', 'practice', :'s3_id', 5);

COMMIT;
